### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by hohl** [getsentry/sentry-laravel#103]
When I'm trying to use this library with **Laravel 5.5** I'm getting an `ErrorException: array_merge(): Argument #1 is not an array` in `/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php:34`. 

That's what's in line 34:

> return call_user_func($this->existingHandler, $code, $message, $file, $line, $context);

Any ideas why this might fail with Laravel 5.5? Is it even caused by this lib? There isn't anything else in the stack trace, but it worked fine before upgrading to 5.5 and I don't use `array_merge` anywhere.

**Comment by stayallive** [comment]
It seems more likely this occurs in the `existingHandler` (whatever the existing handler is in your case), I don't think it's caused by the Sentry lib since I'm running it in a few Laravel 5.5 projects without a problem.

Have you checked the laravel logs or php error logs? That might contain a better stacktrace, or run it locally with debug enabled to see some more context. 

Or do you have other packages that might be adding an exception handler (maybe you can share your composer.json so I can try to reproduce)?

**Comment by hohl** [comment]
Thank you for your help. But after some debugging it just seems the stack trace is somehow broken and the exception doesn't belong to Sentry at all. Stepping through the application shows that the error is raised inside Laravel itself, just no clue why - yet.

**Comment by stayallive** [comment]
@hohl no problem 😉  Happy you found it!

**Comment by foxted** [comment]
@hohl Running into the same issue, can you give details about what fixed it for you?

**Comment by hohl** [comment]
@foxted Sorry for the the (too) late response. But yeah, had the exact same issue.

**Comment by stayallive** [comment]
I would like to add the recommendation to not enable/load Sentry in your testing environment at all :)

**Comment by foxted** [comment]
It wasn't, but somehow got triggered :/

**Comment by hohl** [comment]
Well, it wasn't configured (DSN is only set on the production server) but the library always gets loaded.

**Comment by stayallive** [comment]
Hmm I see some room for improvement there, thanks for all the insights!
