### ISSUE TITLE
Suppor for HttpResponseException

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [getsentry/sentry-laravel#139]
Hi everyone,

I made an API on Lumen, i use Sentry on all our Mobile projects/Python/Rails etc.
On our api all works based on Json, we configured the library but what we can do if we want  to send all "HttpResponseException" based on Json?

Example of our code:
```

try{
  //  our code
} catch(\Exception $error) {
     DB::rollBack();
     //we want to send this to Sentry Logs.
     throw new HttpResponseException(new JsonResponse([
     'message' => 'Error al enviar token',
     'message_exec' => $error->getMessage()
     ], JsonResponse::HTTP_BAD_REQUEST));
}
```

```
 public function report(Exception $e)
    {
        if (app()->bound('sentry') && $this->shouldReport($e)) {
                app('sentry')->captureException($e);
        }
        parent::report($e);
    }  
```

**Comment by stayallive** [comment]
Check out the `$this->shouldReport($e)` function, it excludes a few by default and you can add / remove from the list yourself (depending on the Lumen version).

Simply removing the `$this->shouldReport($e)` check should send all exceptions (but also all 404 exception and tokenmismatches etc.). So better to validate `$this->shouldReport($e)` does not exclude the exception you are trying to catch or whitelist is your self by modifying the check to allow for the `HttpResponseException`.

**Comment by stayallive** [comment]
That is because a `HttpResponseException` is handled by Laravel and "rendered" to a response, and thus not registered as an real exception (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Exceptions/Handler.php#L160-L188). 

This is not something wrong with the Sentry integration. This is the way how Laravel handles some Exceptions that are just used to create a response and allow you to write cleaner code (they are also not logged to log files for example).

----

Having said that...

You could send the exception to Sentry inside the `render` handler (https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L40-L50) which could look something like this:

```php
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        if (app()->bound('sentry') && $exception instanceof HttpResponseException) {
            app('sentry')->captureException($exception);
        }

        return parent::render($request, $exception);
    }
```
