### ISSUE TITLE
Log channels stack trace is inside the message as a string

### ISSUE THREAD

**Issue by sweet-greg** [getsentry/sentry-laravel#184]
Hi,

I recently started using the log channels from Laravel, and I noticed the stack trace is being sent over inside the message. Therefore it's not correctly parsed in Sentry, and error deduplication is broken.
It's related to #142 imo

Here's how the error looks inside of sentry without using log channels
![screenshot 2019-01-31 at 16 43 31](https://user-images.githubusercontent.com/5057847/52065730-6a85cb80-2577-11e9-83a8-3f22937552ac.png)

Here with the log channels
![screenshot 2019-01-31 at 16 32 10](https://user-images.githubusercontent.com/5057847/52065751-740f3380-2577-11e9-94b9-d4514c84784e.png)

My configuration is:
```
'sentry' => [
   'driver'  => 'sentry',
   'level'   => 'debug',
]
```

**Comment by markdwhite** [comment]
It might not be the most efficient solution, but I ended up tapping into an extended inlinelogger that just set a formatter that sanitised the context being sent to Sentry so that duplicates were picked up.

    'sentry' => [
            'driver' => 'sentry',
            'tap' => [Somsip\BlcKnd\Logger\SentryInlineLogger::class],
            'level' => 'error',
     ],

Main code here, but this package contains other stuff so you're probably best just taking what you need:

https://github.com/markdwhite/blc_knd/tree/master/src/Logger

**Comment by stayallive** [comment]
@sweet-greg are you doing this on the `0.x` version or the `1.x` version of the SDK? We changed the handler quite a bit in `1.x` and possibly already fixed this issue so wanted to make sure where I need to look.

**Comment by sweet-greg** [comment]
Hi @stayallive 
I just tested it out with version 1.0.0
Result is the same as before sadly.

**Comment by stayallive** [comment]
@sweet-greg many thanks for testing though, will see if we can figure it out!

**Comment by sweet-greg** [comment]
@stayallive thank you! It's quite an annoying issue. 
For the time being I had to create a global listener for a log event to send it over to sentry.

**Comment by smknstd** [comment]
+1

**Comment by olivernybroe** [comment]
We have the same issue with `^1.9`

**Comment by smknstd** [comment]
All my sentry issues have the message content displayed as text, even with last version (2.4.2). What do I do wrong (I have the default config) ? Thanks for your help !

![Screenshot from 2021-04-28 08-03-17](https://user-images.githubusercontent.com/2412608/116354215-60a3af00-a7f8-11eb-9c0e-15e29d36a05d.png)

**Comment by stayallive** [comment]
@smknstd can you confirm what you have in `config/logging.php`?

And can you possible also show me how this particular exception was logged (where is the `logger()->error()` call or some other way of logging it)?

https://github.com/getsentry/sentry-laravel/blob/65ba0ea34ce124b48f50fb59b80c701bf76f4b12/src/Sentry/Laravel/SentryHandler.php#L209-L213

Because if everything went right `captureException` should be used... but possible the way this particular error is triggered doesnt meet the correct conditions.

**Comment by smknstd** [comment]
As said it is with all issues, including laravel exceptions

![Screenshot from 2021-04-28 14-33-52](https://user-images.githubusercontent.com/2412608/116404386-dd518000-a82e-11eb-9108-fdc1dbcdb268.png)

I think i've got nothing special in config:

```
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'sentry'],
        ],
        ...
        'sentry' => [
            'driver' => 'sentry',
            'level'  => env('SENTRY_LOG_LEVEL', 'error')
        ],
    ],
```

and sentry.php is the same as https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php

**Comment by smknstd** [comment]
It is the same when I manually log something:

```
Log::error("An error occurred ...", [
   "context_data" => "...";
])
```

![Screenshot from 2021-04-28 14-39-28](https://user-images.githubusercontent.com/2412608/116405104-90ba7480-a82f-11eb-81fa-4171ddf463f7.png)

**Comment by stayallive** [comment]
Just to confirm, because I think I'm seeing what you are seeing... but let me know:

I'm seeing this, I think just like you are:

![image](https://user-images.githubusercontent.com/1090754/116452623-32f15100-a85e-11eb-8c02-dc61095b1429.png)

But if I scroll past the wall of text I do get here:

![image](https://user-images.githubusercontent.com/1090754/116452695-47cde480-a85e-11eb-9c22-cce8974a14f4.png)

This is also what is happening for you? The stack trace is there? It's just that the message is also containing the full string of it?

**Comment by smknstd** [comment]
I confirm I see the Exception section with proper breadcrumb. Message section on top is misleading, not the greatest UX I guess ... Thanks for your help :)

**Comment by stayallive** [comment]
Check out version 2.5.0 that was just released and let me know if that looks better 👌
