### ISSUE TITLE
The option "user_context" does not exist.

### ISSUE THREAD

**Issue by zhernosekim** [getsentry/sentry-laravel#185]
I used "sentry/sentry-laravel": "^0.12.0@dev" earlier and it worked with user_context correctly. How to resolve this error for version 1.0-beta?

**Comment by stayallive** [comment]
Look for `user_context` in the [upgrade documentation](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md) of the `sentry-php` the Laravel integration uses. 

I see the user context documentation is currently missing from the Laravel documentation so that will be added back later.

The gist is to do instead of `$client->user_context(['email' => 'foo@example.com']);` do:

```php
use Sentry\Hub;
use Sentry\Scope;

Hub::getCurrent()->configureScope(function (Scope $scope): void {
    $scope->setUser(['email' => 'foo@example.com']);
});
```

**Comment by LeoColomb** [comment]
Indeed. Would be great to update [examples](https://github.com/getsentry/sentry-laravel/tree/4cf6852fd38c8cbd0a52179cfdc74b156866ade4/examples) configs as well.

**Comment by stayallive** [comment]
We never had ik documented in the example since there is no user context in a clean Laravel setup, but it is documented correctly now!

> https://docs.sentry.io/platforms/php/laravel/#user-context

**Comment by LeoColomb** [comment]
> no user context in a clean Laravel setup

Well, yes, but examples do contain `user_context`:

https://github.com/getsentry/sentry-laravel/blob/4cf6852fd38c8cbd0a52179cfdc74b156866ade4/examples/laravel-5.4/config/sentry.php#L13

https://github.com/getsentry/sentry-laravel/blob/39e918a8f2c9d06c7408d275095e36ad4258886d/examples/laravel-5.5/config/sentry.php#L13

**Comment by LeoColomb** [comment]
Ah, OK, these old examples are supposed to stick at the version < 1.
But [they are partly been updated](https://github.com/getsentry/sentry-laravel/commit/8fac7c263cc1ba6a3b44d3db56c34f635ecbbefc#diff-c3b64748734a2278da9bb6ce42e43e49), that why it raises some confusions.

**Comment by stayallive** [comment]
@LeoColomb good point, totally missed those :( Thanks for letting me know!

I updated those example to reflect the config option changes here: #197

**Comment by CharlieEtienne** [comment]
For those who had cache config on remote server and are now trapped in a loop with that error, you must uninstall `sentry/sentry-laravel` by removing it from `composer.json`, deploy, clear config, reinstall sentry, and deploy again.

**Comment by stayallive** [comment]
Alternatively you can remove the config cache file manually: `bootstrap/cache/config.php`.

**Comment by dwightwatson** [comment]
It's a *real* shame that this package stopped supporting sending user details out of the box. It feels incredibly lazy that I need to create a middleware to configure Sentry myself because the Laravel-specific Sentry bridge doesn't do it by itself.

**Comment by stayallive** [comment]
Sorry you feel this way so strongly. 

However, the option to add the user context is not gone but it’s called differently now. 

> https://docs.sentry.io/platforms/php/laravel/#user-context

**Comment by pierrocknroll** [comment]
So this option send_default_pii should be documented in the config/sentry.php

**Comment by stayallive** [comment]
I think we shouldn't because then where do we stop with documenting options in there and syncing their defaults with the base package, there are quite a few and more may be added later at any time. Better to keep that in the documentation IMHO.

For reference, they are all documented here: https://docs.sentry.io/error-reporting/configuration/?platform=php
