### ISSUE TITLE
Create releases and deploys with Artisan

### ISSUE THREAD

**Issue by pelmered** [getsentry/sentry-laravel#190]
It would be great if you could add Artisan commands for creating releases and deploys. That would make it a lot easier to integrate this with CI pipelines.

I don't have time right now, but I could probably submit a PR for this later this spring if you like the idea.

**Comment by Jean85** [comment]
IMHO that would be a great duplication of effort, and it hits a completely different API compared to the one used to report events.

That behavior is already attainable using the Sentry CLI tool: https://docs.sentry.io/cli/
It's a Rust executable, so it's perfectly portable. I personally use the [Docker container](https://hub.docker.com/r/getsentry/sentry-cli) in my CI pipeline, which is even better.

**Comment by stayallive** [comment]
I agree with @Jean85 although we could provide a wrapper for the CLI tool, it's easier for the user and us to just use the CLI tool :)

Otherwise we need to discover the CLI tools location and wrap all it's options and manage versions and differences between version, that will become a mess really quickly and will cause more trouble than it's worth.

The CLI tool is cross-platform and usable on any platform and can do everything you want to do 👍
