### ISSUE TITLE
Uncaught Error: Class 'Raven_Client' not found

### ISSUE THREAD

**Issue by WillemRoman** [getsentry/sentry-laravel#198]
I recenty got this error after upgrading our composer. Did the original Sentry package got updated where the Raven_Client got deprecated or so?

`PHP Fatal error:  Uncaught Error: Class 'Raven_Client' not found in /api/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravel.php:18
Stack trace:
#0 /api/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php(101): Sentry\SentryLaravel\SentryLaravel::getClient(Array)
#1 /api/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Sentry\SentryLaravel\SentryLaravelServiceProvider->Sentry\SentryLaravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /api/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build(Object(Closure))
#3 /api/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('sentry', Array)
#4 /api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make('sentry', Array)
#5 /api/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravel.php on line 18
`

**Comment by stayallive** [comment]
Yes, the 1.0 release of the Laravel integration uses the 2.0 version of the Sentry PHP SDK.

It's a complete overhaul and changes a lot. It should however be relatively straight forward assuming you we're doing some custom context and sending your own exceptions.

The upside of the 2.0 PHP SDK is that no matter if Laravel or Symfony or plain PHP (or another language even) the functions and ways you interact with the client are all called the same / used the same.

A few links that can get you started:

- https://docs.sentry.io/platforms/php/laravel/
- https://docs.sentry.io/error-reporting/capturing/?platform=php

**Comment by vitanivanov** [comment]
I had the same error, bumped the version to 1.0 as per the documentation.
I changed the configuration file and everything seems to be OK.
However, the captureException method does not report to Sentry.
"php artisan sentry:test"successfully generates an event, but I cannot verify anywhere that it has been received.
Any ideas why?

**Comment by mdzhokanov** [comment]
> Yes, the 1.0 release of the Laravel integration is a breaking change because it uses the 2.0 version of the Sentry PHP SDK.

@stayallive , you must be kidding us. What you did (to break an official version that has been stable for almost 3 years) is against any versioning management best practice. Furthermore, your breaking change was against the official Composer guideline. I really don't get how come your change has passed through a revision process, but whatever ...

If any other engineer hits this problem, here is your solution. Simply change:
```
    "require": {
        "sentry/sentry-laravel": "0.8.0"
    },
```

to

```
    "require-dev": {
        "sentry/sentry-laravel": "dev-master#3deb3b26a0608b653284388e13531530205a786a"
    },
```


 0.8.0

**Comment by Jean85** [comment]
> What you did (to break an official version that has been stable for almost 3 years) is against any versioning management best practice. Furthermore, your breaking change was against the official Composer guideline.

To what guidelines are you referring to? Composer tries to follow Semantic versioning, and [basically all Composer constraints](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators) use that spec (or subset of it). Furthermore, they even recently joined the SemVer team: https://github.com/semver/semver/issues/495.

If you read through the SemVer spec, [point 8](https://semver.org/#spec-item-8) says that any kind of breakage is allowed (only) between major versions, and [point 4](https://semver.org/#spec-item-4) says that any 0.x version is to be considered unstable, and API changes are to be expected.

This was a major version increase, and furthermore starting from an unstable one.

Lastly, I invite you to be more kind toward the maintainer, which is devoting his free time to work on this package.

**Comment by stayallive** [comment]
@vitanivanov that is odd, running `php artisan sentry:test` should output something like this:

```
[sentry] Client DSN discovered!
[sentry] Generating test event
[sentry] Sending test event
[sentry] Event sent with ID: somelongidiremovedhere
```

This event should show up in your dashboard for the project you have configured the DSN for on Sentry.io. You can paste the event ID (from your own output) in the search bar to jump straight to the issue which should state "This is a test exception sent from the Sentry Laravel SDK.".

**Comment by vitanivanov** [comment]
> @vitanivanov that is odd, running `php artisan sentry:test` should output something like this:
> 
> ```
> [sentry] Client DSN discovered!
> [sentry] Generating test event
> [sentry] Sending test event
> [sentry] Event sent with ID: somelongidiremovedhere
> ```
> This event should show up in your dashboard for the project you have configured the DSN for on Sentry.io. You can paste the event ID (from your own output) in the search bar to jump straight to the issue which should state "This is a test exception sent from the Sentry Laravel SDK.".

There seems to be something heavily environment/configuration dependent in the new version.
I did presumably all the required steps, and was still unable to get the errors in Sentry, even though the sentry:test artisan command seemed successfully executed.
This was fixed when adding a cacert in **php.in**, but exceptions were still not received by Sentry.

**Comment by Arkanius** [comment]
I agree with @mdzhokanov, my apps just broke. I undestand that it's a breaking change but it's not easy to go back. I'm trying to go bck to 1.0.0 version and still not working.
Again, I understand that it is a breaking change; but, a breaking change should not be so difficult to rollback.

**Comment by stayallive** [comment]
Probably why you are having trouble going back is because you are trying to go back to 1.0 which is actually the new version we just released (which has the breaking change). 

If you go back to `0.11.0` you should be all set and back to how it was before 👍 

The breaking change is happening on the bump from `0.11.0` to `1.0.0`.

**Comment by Arkanius** [comment]
Worked! Thanks

**Comment by ste93cry** [comment]
Just to make a few things clear:

>I undestand that it's a breaking change but it's not easy to go back. I'm trying to go bck to 1.0.0 version and still not working.
Again, I understand that it is a breaking change; but, a breaking change should not be so difficult to rollback.

Since breaking changes should only happen between major versions (this is what is written in the Semver specs as said by @Jean85), the only way your app broke is because you deliberately upgraded the Composer constraints from something like `^0.x` to `^1.0`, which means that you should be aware that being a new major version things will likely break (otherwise it wouldn't be a major version bump) and this is valid for any library following these specs. To revert back, obviously, you have to downgrade to the previous release (`0.x`) so I don't really understand why you said that you were trying to go back to `1.0` which was the version you were at in that moment

>I strongly recommend mentioning somewhere in the install / support documentation that the **curl.cainfo** configuration option in **php.ini** is mandatory for the out-of-the-box client that sentry-laravel uses

This may be a good point indeed for a note in the documentation, please note that some systems are already pointing to the correct CA bundle path and some not.

>you must be kidding us. What you did (to break an official version that has been stable for almost 3 years) is against any versioning management best practice. Furthermore, your breaking change was against the official Composer guideline.

@mdzhokanov actually I don't want to start a discussion about this because I believe we all agree it would not be useful to anyone, but as explained by @Jean85 any kind of breaking change is allowed between `0.x` releases and between major versions bump, so what you said is totally incorrect and I strongly recommend you to read the specs before starting such rant against a person that is devoting his free time to the community. Also I remember everyone that if constraints are set correctly in your `composer.json` then Composer will never upgrade libraries between major version bumps, so this is something that you must do deliberately and in turn this means that if you know the Semver specs then you know that doing this will likely result in more work from your side since BC breaks are expected

**Comment by vitanivanov** [comment]
> Just to make a few things clear:
> 
> > I undestand that it's a breaking change but it's not easy to go back. I'm trying to go bck to 1.0.0 version and still not working.
> > Again, I understand that it is a breaking change; but, a breaking change should not be so difficult to rollback.
> 
> Since breaking changes should only happen between major versions (this is what is written in the Semver specs as said by @Jean85), the only way your app broke is because you deliberately upgraded the Composer constraints from something like `^0.x` to `^1.0`, which means that you should be aware that being a new major version things will likely break (otherwise it wouldn't be a major version bump) and this is valid for any library following these specs. To revert back, obviously, you have to downgrade to the previous release (`0.x`) so I don't really understand why you said that you were trying to go back to `1.0` which was the version you were at in that moment
> 
> > I strongly recommend mentioning somewhere in the install / support documentation that the **curl.cainfo** configuration option in **php.ini** is mandatory for the out-of-the-box client that sentry-laravel uses
> 
> This may be a good point indeed for a note in the documentation, please note that some systems are already pointing to the correct CA bundle path and some not.
> 
> > you must be kidding us. What you did (to break an official version that has been stable for almost 3 years) is against any versioning management best practice. Furthermore, your breaking change was against the official Composer guideline.
> 
> @mdzhokanov actually I don't want to start a discussion about this because I believe we all agree it would not be useful to anyone, but as explained by @Jean85 any kind of breaking change is allowed between `0.x` releases and between major versions bump, so what you said is totally incorrect and I strongly recommend you to read the specs before starting such rant against a person that is devoting his free time to the community. Also I remember everyone that if constraints are set correctly in your `composer.json` then Composer will never upgrade libraries between major version bumps, so this is something that you must do deliberately and in turn this means that if you know the Semver specs then you know that doing this will likely result in more work from your side since BC breaks are expected

The version in **composer.json** was **"^0.8.0"**.
However, for some reason, when updating, **sentry/sentry** got updated from 1.2 to 2.0,

**Comment by ste93cry** [comment]
As you can see [here](https://semver.mwl.be/#?package=sentry%2Fsentry-laravel&version=%5E0.8.0&minimum-stability=stable) it's not possible that Composer would have updated the version. I've also just tried the following that confirms this:

```sh
docker run --rm --interactive --tty --volume $PWD:/app composer require sentry/sentry-laravel:"^0.8.0"
```

This in a empty folder will install `sentry/sentry-laravel 0.8.0` and `sentry/sentry 1.10.0` (at the time of writing)

Let's now do `composer update`

```sh
docker run --rm --interactive --tty --volume $PWD:/app composer update
```

This results into the message `Nothing to install or update` and versions of both libraries are still like the first run. This is not to say I don't trust what you're saying, but that for sure something else must have happened to cause such a bump and so it's not really fault of @stayallive. Said this I don't want to start a war on who is right :wink: 

>It took me approximately 8 hours of debugging the sentry/sentry package to realize that the events were sent but were not received because of the lack of valid SSL certificate.
In version 0.8 such a thing was not necessary, so this is a hidden dependency when upgrading from 0.8.0 to 1.0

It used to work in `1.x` because that version was shipping with a (non-updated btw) CA bundle that was used by default. I don't know if an exception is thrown in case the SSL check fails (and then it gets catched by our error handler which in turn will fail to report for this reason) but if that's the case maybe it would be better to just leave it throwing and let the user see it instead of failing silently. WDYT?

>I understand that breaking changes are inevitable, but from a user perspective you need an upgrade guideline. Take Laravel for example: https://laravel.com/docs/5.8/upgrade

We have such guide [here](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md).

**Comment by vitanivanov** [comment]
> As you can see [here](https://semver.mwl.be/#?package=sentry%2Fsentry-laravel&version=%5E0.8.0&minimum-stability=stable) it's not possible that Composer would have updated the version. I've also just tried the following that confirms this:
> 
> ```shell
> docker run --rm --interactive --tty --volume $PWD:/app composer require sentry/sentry-laravel:"^0.8.0"
> ```
> 
> This in a empty folder will install `sentry/sentry-laravel 0.8.0` and `sentry/sentry 1.10.0` (at the time of writing)
> 
> Let's now do `composer update`
> 
> ```shell
> docker run --rm --interactive --tty --volume $PWD:/app composer update
> ```
> 
> This results into the message `Nothing to install or update` and versions of both libraries are still like the first run. This is not to say I don't trust what you're saying, but that for sure something else must have happened to cause such a bump and so it's not really fault of @stayallive. Said this I don't want to start a war on who is right 😉
I suspect a transitive dependency issue - something else must have been updated which forced the sentry/sentry  update to 2.0. Probably a Laravel package? I suggest verifying it with the default packages required for Laravel 5.5.

> It used to work in `1.x` because that version was shipping with a (non-updated btw) CA bundle that was used by default. I don't know if an exception is thrown in case the SSL check fails (and then it gets catched by our error handler which in turn will fail to report for this reason) but if that's the case maybe it would be better to just leave it throwing and let the user see it instead of failing silently. WDYT?
The easiest way to check it is this:
1. Remove the ca cert reference from the php.ini of the PHP CLI.
2. Execute "php artisan sentry:test"
An event will be generated - it will have an ID and everything, but it will not be received by Sentry.
People testing on local dev environments will be affected by a silent failure and will be puzzled like me for hours. I suggest either throwing an exception or logging an error somewhere.

> We have such guide [here](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md).
I linked the Laravel upgrade guide, because I recently did the procedure for 5.1 to 5.5 and it was quite straightforward. Instead of listing all the changes, I suggest a more user-friendly approach - what I need to change and where.

**Comment by Jean85** [comment]
> but all I really needed was a step "add a valid ssl certificate in your php.ini file", which would have saved 8 hours for me.

This seems an issue with the transport layer, which is not our, but it's Curl. I'll dig into that.

**Comment by ste93cry** [comment]
>The Curl transport should've blown up with an exception: https://github.com/php-http/curl-client/blob/master/src/Client.php#L142-L143

Since we're catching all exceptions (even while handling another error) we have the classic case of the dog biting its own tail because each error will fail to be reported and the user will know nothing about the problem because it's "silenced". We should investigate whether we can catch such exceptions (e.g. network exceptions) and throw them letting the app blow up like it would normally do so that the developer knows that something gone wrong

**Comment by robinnydahl** [comment]
For you guys having problems with Sentry going from `0.8.0` directly to `1.0.0`, go back to `0.11.0` as mentioned by @stayallive.

We have multiple deployments daily and when we reverted back to `0.8.0` (as we had before the issue) we still got the exception above. Why we never got upgraded to `0.11.0` in the first place still amazes me... Probably due to how we initially set up Sentry, following the Official Sentry Documentation for Laravel.

**Comment by stayallive** [comment]
We figured out why this is happening and where we wen't wrong, so here is the solution for downgrading problems.

Because of incorrect version constraints on `sentry/sentry-laravel` version `0.8` and lower it allows for `sentry/sentry` version `2.0` to be installed (which has the breaking changes) but `sentry-laravel` below version `1.0` is not compatible.

The constraint on version `0.8` of the Laravel integration was to require `sentry/sentry:>=1.7.0` this also includes `2.0` ([visualized](https://semver.mwl.be/#?package=sentry%2Fsentry&version=%3E%3D1.7.0&minimum-stability=stable)), in `0.9` we switched to the correct constraint of `sentry/sentry:^1.9.0` ([visualized](https://semver.mwl.be/#?package=sentry%2Fsentry&version=%5E1.9.0&minimum-stability=stable)).

So to fix install `sentry/sentry-laravel` of at least version `0.9`, but better ofcourse being the latest `0.11` release which correctly only installs `1.x` of the PHP SDK.

So if you are still on `0.8` of the Laravel integration and or trying to downgrade to `0.8` (or lower) you will still install the `2.0` of the PHP SDK.

We will work on getting hotfixes out for the older versions fixing the constraints!

**Comment by stayallive** [comment]
I am closing this since all the hotfixes are out all the way back to `0.3` (please upgrade!) so downgrading results in going back to `1.x` of the base SDK and only `1.x` of the Laravel integration will pull in `2.x` of the base SDK as it should.

Thank you all for the reports and information!
