### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by SreejithEzhakkad** [getsentry/sentry-laravel#211]
Support Required for  Larave 5.8. [sentry-laravel](https://github.com/getsentry/sentry-laravel/) does not support Laravel 5.8. Please add support to this version. I am unable to upgrade my Laravel project from 5.7 to 5.8 due to this. 

![screenshot--2019 03 12-10-54-23](https://user-images.githubusercontent.com/19388006/54176593-7a1cfc00-44b5-11e9-8405-d0892a38a5ba.png)

**Comment by stayallive** [comment]
We do already support 5.8 (since a few days before the release even) but you'll need `getsentry/sentry-laravel` version `1.0`.

Do keep in mind this also upgrades the underlying PHP SDK to 2.0 which has some breaking changes, check out the [docs](https://docs.sentry.io/platforms/php/laravel/) for more information if needed.
