### ISSUE TITLE
Laravel 5.5 with PHP 7.0 Not working

### ISSUE THREAD

**Issue by yashweb3** [getsentry/sentry-laravel#215]
![image](https://user-images.githubusercontent.com/48712509/54591948-53c90480-4a51-11e9-97f6-f7c03139ab19.png)

 Problem 1
    - Installation request for sentry/sentry-laravel 1.0.1 -> satisfiable by sentry/sentry-laravel[1.0.1].
    - sentry/sentry-laravel 1.0.1 requires php ^7.1 -> your PHP version (7.0.30) does not satisfy that requirement.

in document no any solution for that.

**Comment by stayallive** [comment]
@yashweb3 as documented in the [readme](https://github.com/getsentry/sentry-laravel#laravel-version-compatibility) we only support PHP 7.1 and higher starting from version 1.0 of our Laravel integration.

You can use `^0.11` if you need to install the Laravel integration on PHP 7 or lower.

**Comment by yashweb3** [comment]
You can use ^0.11 if you need to install the Laravel integration on PHP 7 or lower.


'providers' => array(
    // ...
    Sentry\Laravel\ServiceProvider::class,
)

'aliases' => array(
    // ...
    'Sentry' => Sentry\Laravel\Facade::class,
)

it will not be working with an old version(^0.11)

**Comment by stayallive** [comment]
0.x is a bit different than 1.x so the installation instructions are also a bit different and currently not on docs.sentry.io because of 1.x.

Check out the docs here: https://github.com/getsentry/sentry-laravel/tree/0.x#installation

But keep in mind that on Laravel 5.5 you don't have to register the providers yourself because the package auto-registers itself (new feature since Laravel 5.4).

**Comment by yashweb3** [comment]
Check out the docs here: https://github.com/getsentry/sentry-laravel/tree/0.x#installation

Thanks a lot it working fine for me :)

**Comment by stayallive** [comment]
Pefect. Happy to hear!
