### ISSUE TITLE
Laravel sentry also catch vue errors?

### ISSUE THREAD

**Issue by jlcanizales** [getsentry/sentry-laravel#230]
Hello,
Im using Sentry in my Laravel proyect and it works like a charm when I have errors on blade and  controllers, but im not sure if this catch vue.js errors, can anyone tell me please if this works with the current sentry-caravel package

**Comment by stayallive** [comment]
Hey @jlcanizales `sentry-laravel` only captures PHP errors, so not Vue errors since those are client side JavaScript.

For that you also need to implement (next to Sentry Laravel) the Browser SDK, the documentation for that you can find here: https://docs.sentry.io/platforms/javascript/?platform=browser

And there is also a Vue integration: https://docs.sentry.io/platforms/javascript/vue/

This is not something the Laravel integration will configure/provide for you because of wildy different front-end setups.

**Comment by luckylooke** [comment]
Hi @jlcanizales have you successfully setup your tracking? Because I have also difficulties with logging vue errors to sentry in Laravel+Vue environment. https://github.com/getsentry/sentry-javascript/issues/3334
:pray:

**Comment by jlcanizales** [comment]
> Hi @jlcanizales have you successfully setup your tracking? Because I have also difficulties with logging vue errors to sentry in Laravel+Vue environment. [getsentry/sentry-javascript#3334](https://github.com/getsentry/sentry-javascript/issues/3334)
> 🙏

as mention stayallive I use the javascript method to get the vue error, I haven't tried with the vue integration, you have to make sure that you are using the dns of your proyecto, not the one that sentry gives as an example

**Comment by luckylooke** [comment]
@jlcanizales thanks for info, finally I have found the reason, as we are using older version on BE, I had to dowgrade integration:
 from `@sentry/vue@6.2.2` to `@sentry/vue@5.30.0`.  :+1: 
 
 Thanks for your input anyway, happy coding :)
