### ISSUE TITLE
Configure basic auth for selfhosted sentry

### ISSUE THREAD

**Issue by 4n70w4** [getsentry/sentry-laravel#240]
Hi! How best way to configure this library to transfer exceptions to my self-hosted sentry with basic authorization?

**Comment by stayallive** [comment]
You can use the [client builder decorator](https://docs.sentry.io/platforms/php/laravel/#decorating-the-client-builder) to set a custom [transport factory](https://docs.sentry.io/platforms/php/#transport) and set any option you want on the transport of choice including basic authentication if needed.

Sorry this issue was forgotten and you did not get a reply earlier from us!
