### ISSUE TITLE
Disable when debug is enabled?

### ISSUE THREAD

**Issue by royduin** [getsentry/sentry-laravel#243]
In `app/Exceptions/Handler.php` I've:
```
if (app()->bound('sentry') && ! config('app.debug') && $this->shouldReport($exception)) {
    app('sentry')->captureException($exception);
}
```

So if debug is enabled nothing is send to Sentry. At least, that's what I'm expecting. With:
```
Route::get('exception', function () {
    throw new Exception('Test exception');
});
```
That's the case, but with
```
Route::get('exception', function () {
    dump($test);
});
```
It's not, the exception will be send to Sentry:
```
ErrorException (E_NOTICE)
Undefined variable: test
```

So not all errors go through the exception handler, how can I accomplish the same for all errors?

**Comment by stayallive** [comment]
Hey @royduin, exceptions and errors (like E_NOTICE) are very different.

Unhandled exceptions are caught by the handler you have disabled because Laravel handles those and there is no global hook for us to also catch them. 

However the PHP errors (the `E_*` constants) are still caught by Sentry because there is a global hook for those.

Two options to fix:

---

Do no set the DSN locally (or set it to `null`) (see also: https://docs.sentry.io/platforms/php/laravel/#local-development). This will fix it.

---

But if you still want to have a DSN set locally you can also do the following in `config/sentry.php`:

```php
'dsn' => env('APP_DEBUG', false) ? null : env('SENTRY_LARAVEL_DSN'),
```

---

You don't need the debug check in the exception handler in both options then.

**Comment by royduin** [comment]
Thanks @stayallive, I though this was different in the past but I'll go for the second option 😎
