### ISSUE TITLE
ServiceProvider::register() may pull app('log') from container before config('logging') has been loaded

### ISSUE THREAD

**Issue by pdbreen** [getsentry/sentry-laravel#253]
Lumen specific

ServiceProvider::register() is calling `app('log')` to check if it should register as channel.  This, of course, has a side effect of instantiating the logging interface.  In Lumen, this could happen prior to `$this->app->config('logging')` resulting in an incorrect configuration of the logger.

Within the `instanceof Lumen` check, it seems like both 'sentry' and 'logging' configs should be loaded.

**Comment by stayallive** [comment]
Interesting. However I do feel this is "correct" behaviour. 

Lumen is a bit odd in that you can indeed register the service providers before loading your config but this seems incorrect since config might be used to register service providers (as in this case).

However this is also a bit of a chicken and egg problem we might not be able to fix. Because you can't add Sentry as a logging driver before it's registered and it needs to be registered before the logging service is booted. Also configure is always called before loading the LogManager (https://github.com/laravel/lumen-framework/blob/0f450f8d6ee47bdef6c88a2492883c6e48a33a95/src/Application.php#L451-L458) so this is only an issue when using your own config files.

My advice would be to always configure your config's before registering any service providers (always do you configuration [here](https://github.com/laravel/lumen/blob/c25833addaff0db442614f7539d22d66fd1919fb/bootstrap/app.php#L9-L26) for example).

**Comment by pdbreen** [comment]
As general practice, we do -- but, of course, then we want Sentry registered before the config loaders just in case there is an issue in one of the configs, so we pull it ahead.  It was easy enough to repair by loading the logging config earlier as well, just a unexpected side effect.
