### ISSUE TITLE
Options to disable SQL and log breadcrumb

### ISSUE THREAD

**Issue by leo108** [getsentry/sentry-laravel#257]
We don't want to send SQL and logs to Sentry, it there a way to disable them?

**Comment by stayallive** [comment]
@leo108 they only thing we currently support disabling is the PII (automatic user ID, which should be disabled by default and controlled by the `send_default_pii` config option) and [SQL bindings](https://github.com/getsentry/sentry-laravel/blob/043b2943395df86aa924490d4d5360e100c67c54/config/sentry.php#L13).

I would be happy to accept a PR or look into adding an option for this. Could you maybe tell us a bit about why you would want to disable all this information since generally it's helpful info, curious if there is a reason why you don't want them.

**Comment by leo108** [comment]
PR created.

**Comment by leo108** [comment]
@stayallive any feedback on the PR?
