### ISSUE TITLE
Setting timeout option in new sentry version

### ISSUE THREAD

**Issue by Siva-93** [getsentry/sentry-laravel#259]
Hi,

Recently I have upgraded my laravel sentry sdk version from 0.8 to 1.1.0.

In the old version, I have following 
`array(
    'dsn' => getenv('SENTRY_DSN'),

    // capture release as git sha
    'release' => getenv('GIT_HASH') ?: 'unknown',

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => false,  /*turned off due to excessive number of bgtask queries causing json_encode() problems*/

    // Capture default user context
    // 'user_context' => true,

    'environment' => getenv('APP_ENV') ?: 'unknown',

    // 'timeout' => (isDevEnvironment() ? 10 : 1),

    // 'exclude' => [
    //     'NoLogException'
    // ]
);`

The "timeout", 'user_context', 'exclude' are not working. I have found the equivalent functionality for user_contect and exclude option. But I don't know how to configure the **timeout**.

@stayallive https://github.com/getsentry/sentry-laravel/issues/68#issuecomment-516571657 you answer partially answered my question. May I know how to configure the curl client timeout?

Thank you.

**Comment by stayallive** [comment]
This recently came up again in the original SDK and it was decided to not bring back the timeout option (or any HTTP transport options).

> https://github.com/getsentry/sentry-php/pull/967#issuecomment-585810749

You can use the [client builder decorator](https://docs.sentry.io/platforms/php/laravel/#decorating-the-client-builder) to set a custom [transport factory](https://docs.sentry.io/platforms/php/#transport) and set any option you want on the transport of choice.

Sorry this issue was forgotten and you did not get a reply earlier from us!
