### ISSUE TITLE
Method [captureException] is not supported by Sentry or no User has been set on Sentry to access shortcut method.

### ISSUE THREAD

**Issue by wanghoneygit** [getsentry/sentry-laravel#265]
I want use sentry, but raise error:

result:
![image](https://user-images.githubusercontent.com/20147781/63516511-95d60500-c51f-11e9-8844-049839b7f050.png)

this is my think:"jacopo/laravel-authentication-acl" conflicts with "sentry/sentry-laravel"

this is part of composer.json
![image](https://user-images.githubusercontent.com/20147781/63516209-25c77f00-c51f-11e9-987d-db8bf1d67e26.png)

**Comment by stayallive** [comment]
@wanghoneygit it does conflict! The ACL package uses a package called "Sentry".

This sentry package provides autorization and because it has the same name it conflicts. We have a solution for that: https://docs.sentry.io/platforms/php/laravel/#resolve-name-conflicts-with-packages-also-called-sentry

If you follow the instructions above you should be good to go!

**Comment by stayallive** [comment]
Because I have not heard back I am going to assume my directions were sufficient and the problem was solved, closing this issue, feel free to reopen or open a new one if there are still unsolved issues.
