### ISSUE TITLE
Not working on fresh Laravel v5.8.35

### ISSUE THREAD

**Issue by sghimself** [getsentry/sentry-laravel#281]
I tried to send exceptions and messages on fresh Laravel v5.8.35 install. Configuration same as in manual. Exception handling and using methods inside code `captureMessage($message)` and `captureException($exception)` returns UUID of event but I can't find it in Sentry. 

Fresh `Laravel v5.8.35` with default config
`PHP 7.1.29` on Windows 10 PRO

**Comment by stayallive** [comment]
Sentry works by sending on best effort and to prevent infinite loops transport errors are ignored and I think what is happening is that your PHP is configured without a correct `openssl.cafile` as explained here: https://stackoverflow.com/a/39812970/1580028. This can cause requests to sentry.io to fail and events are then never arriving although it looks like they were correctly sent.

Can you try setting up the `openssl.cafile` configuration if you don't already and see if that fixes it for you?

Related and possibly the same issue: https://github.com/getsentry/sentry-laravel/issues/181#issuecomment-455616463

**Comment by sghimself** [comment]
This is it! Thanks @stayallive for help :) I set up OpenSSL, but I completely forgot about `openssl.cafile` and that's why I rejected this idea. 

Maybe it's a good time to add this notice to readme.md or change application to throw an exception or something else ? This issue stopped me for a long time...

**Comment by stayallive** [comment]
Yeah that might not be a terrible idea, however this is really a environment configuration issue and not something we want to guard against, this will break all https requests in your app not just Sentry.

The reason we don't throw an Exception is because Sentry would capture that again which could quickly snowball out of control. However we are working on improving the debugging situation, so this will be less of an issue later.
