### ISSUE TITLE
Spike in file I/O after install

### ISSUE THREAD

**Issue by adwinying** [getsentry/sentry-laravel#307]
Hello,

I've tried to install `sentry-laravel` but after I did so I realized an overall slowdown of my application, even when sentry is not enabled (no DSN key inserted). 

Does this package read/write to some cache somewhere?

**Comment by stayallive** [comment]
Hi @adwinying, no Sentry itself does not write to the cache of some sorts or write any files for that matter.

How did you come to the conclusion it must be I/O?

The one thing that could be happening is that Sentry is sending events which is a network request and cause slowdowns, is it possible your app generates events every request or maybe even multiple per request?

**Comment by adwinying** [comment]
@stayallive Thanks for replying.

I tried running it on two different environments, and the one with slowdown has the source code mounted on an NFS drive. On top of that, I received sqlite file I/O errors, as well as general slowdowns in the command line when navigating within directories after installing sentry.

Currently, I also have Filebeat running (which monitors laravel log files), but I doubt Filebeat would cause any conflicts with sentry 🤔

**Comment by stayallive** [comment]
@adwinying Ah that sounds highly specific and next to impossible for us to track down considering the environment you are in. I think you'll need to do some more digging, happy to provide any support I can but I'm not convinced yet Sentry is doing something that can cause this (I run multiple apps with `sentry-laravel` on NFS based installations without issues).

After changing your vendor directory it is possibly to have some slowing down while NFS catches up. 

However assuming nothing is being written to the Laravel logs (have you checked that?) there is nothing Sentry writes itself (unless it crashes for some reason but hat should be written to the laravel logs) so I doubt that is the issue.

Assuming the slowdown is indeed on the filesystem I think we can rule out Sentry sending events causing the slowdown since that's all network and PHP resources.

---

Unrelated to Sentry but some possible causes to double check:

(Assuming you are using OPCache) Your OPCache might be full after changing the vendor files (adding Sentry) causing excessive I/O because it can't cache the new files. You can try checking that or just restart PHP-FPM to clear it.

Also did you make sure to dump an optimized autoloader file, that is also a possible cause for more disk reads?

**Comment by Jean85** [comment]
I would suggest to use some profiling tool like Blackfire.io or Tideways do find the source of the bottleneck.

**Comment by stayallive** [comment]
@adwinying have not heard from you for while, I'll assume you found the cause / found a fix. If there is still a problem please re-open or create a new issue.
