### ISSUE TITLE
zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by jstolp** [getsentry/sentry-laravel#315]
I'm having trouble with the latest update of sentry/sentry. our dependency guard doesn't like the abandoned package _zendframework/zend-diactoros_ wich is referenced as a dep.

Can i do anything about that?

sentry/sentry : v2.2.6

zendframework/zend-diactoros:

Repository abandoned 2019-12-31
This repository has moved to laminas/laminas-diactoros.

**Comment by stayallive** [comment]
Nope. But don't worry, work is already done to replace the Zend library.

See: getsentry/sentry-php#945 and getsentry/sentry-php#947

I will repeat it here, you can safely disregard the warning it will be fixed in the coming days, it has no effect on your application whatsoever (except for that notice when running `composer` commands).

**Comment by jstolp** [comment]
@stayallive No problem. Thanks for the info. Multiple repo's are stuck with the same problem.

**Comment by jadamec** [comment]
Anything new about this, please? Cannot update other packages... Thanks!

**Comment by stayallive** [comment]
The base PHP SDK just got an update to version [2.3.0](https://github.com/getsentry/sentry-php/releases/tag/2.3.0) which replaces the deprecated dependency. Run `composer update` to get it!

Thank you all for your patience!
