### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by Christophvh** [getsentry/sentry-laravel#324]
Hi,

Happy customer for sentry, but the last few versions having a lot of issues. The documentation has been updated recently and it is not clear anymore what the recommended approach is for installing sentry on Laravel

In older projects I always just did this:

```
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

And everything worked perfectly. In the current documentation there is this:
https://docs.sentry.io/platforms/php/laravel/#log-channels

Why would I configure log channels for sentry? Is this the new recommended approach, should I implement both? Should I choose one? In most projects, I implement both, but this just results in getting a ton of unwanted errors like the classic 'Mysql has gone away'

**Comment by stayallive** [comment]
Hi @Christophvh, I'm very sorry you find it confusing I changed the docs and thought it was better structured and more clear this way.

Did you follow along with the installation section?

https://docs.sentry.io/platforms/php/laravel/#laravel-5x--6x

Please let me know if anything about that is pointing you towards log channels or confusing you and how you think we can improve!

We do not mention log channels there and the installation section is still the recommended route to take since log channels have some issues on their own and can cause a lot of noise, it's completely optional. It's also mentioned on the log channels section but using the approach from the installation docs together with log channels is unsupported and might cause duplicated events.

**Comment by Christophvh** [comment]
My main question was what does the log channel actually provide? Is it only so we can do: Log::channel('sentry') in parts of our code? But I will revert back to only using the report method. Thanks for the quick answer.
