### ISSUE TITLE
out-of-memory after successful Artisan command

### ISSUE THREAD

**Issue by aand18** [getsentry/sentry-laravel#355]
I'm seeing these errors in the logs after activating `sentry-laravel` and running an Artisan command. The command runs successfully, but after some minutes I see these erros:

```log
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) 
        in \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 28672 bytes) 
        in \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) 
        in \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 131072 bytes) 
         in \vendor\sentry\sentry\src\HttpClient\Plugin\GzipEncoderPlugin.php on line 5
```

## Software versions
PHP         `v7.2`
Laravel       `v6`
Sentry-laravel  `v1.8.0`

```php
// config/sentry.php
    'breadcrumbs' => [
        'logs' => true,
        'sql_queries' => true,
        'sql_bindings' => true,
        'queue_info' => true,
        'command_info' => true,
    ],
```

My artisan command reads some files, inserts some data in MySQL (usually more than 100 INSERTs) and exits.

Before, when running version `1.7.0` I was seeing the error and breadcrumbs in  Sentry: 

![image](https://user-images.githubusercontent.com/36073609/84647101-496f1200-af03-11ea-9c72-6700ae1d9fb9.png)

**Comment by stayallive** [comment]
Looking at your screenshot it's possible this command collects too much breadcrumbs and that balloons the size causing this issue.

You can try and adjust the `max_breadcrumbs` setting in your `config/sentry.php` (you need to add that setting yourself), the default is `100` you can try lowering it to see if that helps and/or disable `sql_bindings` or `sql_queries` in the breadcrumbs config section.

It does seem like there was an event generated inside the artisan command otherwise the breadcrumbs would be discarded and it would not end up in the `HttpClient` trying to sent something.

**Comment by aand18** [comment]
@stayallive thank you for pointing me in the right direction.

I wasn't seeing anything in the PHP error logs. I missed the Laravel logs, where warnings were actually present. I have `SENTRY_LOGGING_LEVEL=warning`.

My command calls `warning()` and that's the event that Sentry tries to capture.

How would one go about profiling the memory requirements of Sentry. How can I tell how many breadcrumbs are too many?

**Comment by stayallive** [comment]
That highly depends on what is inside the breadcrumbs so there is not really a good way to say x breadcrumbs will fit inside the memory limit (although I think we could argue that 10 should always fit).

Most applications use a fraction of the memory they're assigned (with CLI scripts being the notable exception) and thus was `100` chosen as a sane default, however for some applications (and thus mostly import/export/data CLI commands) this is too many because of the query (bindings).

So this is very application and also memory limit dependant so I'm afraid I cant give you any good pointers except to "try it out" and see what works for you.
