### ISSUE TITLE
Laravel 7x and Envoyer Deployment: Fatal error: Uncaught ReflectionException: Class sentry does not exist

### ISSUE THREAD

**Issue by SuperlativeEntity** [getsentry/sentry-laravel#370]
Laravel Framework 7.25.0
PHP Version: PHP 7.4.9 (cli)
Package Version: 1.8.0

Using 

`app('sentry')->captureException($exception);`

I get the following error when deploying on Envoyer

Fatal error: Uncaught ReflectionException: Class sentry does not exist in /home/forge/...

PHP 7.4.7 (cli) on Windows 10 works without any issues

**Comment by stayallive** [comment]
This is most likely because config caching, try running `php artisan config:clear` in your server to see if that fixes it, and/or make sure `SENTRY_LARAVE_DSN` is specified in your `.env` on your server.

Other possibility is that you have not committed the changes to your `composer.lock` and thus Sentry is never installed, I believe you should be able to see that in the output of the composer install step in the Envoyer interface.

If that all is done, can you share your `composer.json` so I can take a look?

**Comment by SuperlativeEntity** [comment]
Thanks for the reply! I disabled it on the first deploy and then re-enabled it for any subsequent deploys and it seems okay now.

**Comment by stayallive** [comment]
Interesting maybe some code runs before the composer install action. Glad you got it working 💪
