### ISSUE TITLE
Logging Errors and catched Exceptions

### ISSUE THREAD

**Issue by ruedigerm-playster** [getsentry/sentry-laravel#383]
If I understand the recommended implementation 
```
    public function report(Exception $exception)
    {
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }
        parent::report($exception);
    }
```
 
properly, this we only ever send uncatched exceptions to Sentry, right?
It will not log anything for 

- catched exceptions
- other errors that Laravel throws out-of-the-box like _invalid route_

Is there a recommended way to also log all these kind of errors?
Maybe it would be useful to extend the documentation on this. 
Thanks

**Comment by stayallive** [comment]
Hi @ruedigerm-playster,

This is correct, however also not, I hope I can explain it for you:

> properly, this we only ever send uncatched exceptions to Sentry, right? It will not log anything for
> catched exceptions and other errors that Laravel throws out-of-the-box like invalid route

catched exceptions will indeed not be capture since they we're caught and handled by the developer, PHP wouldn't even let us see captured exception if we wanted to, however if you want to log captured exceptions you can do this:

```php
try {
	// Bad code throwing exceptions
} catch(\Exception $e) {
	// Log the exception to Sentry
	if (app()->bound('sentry')) {
		app('sentry')->captureException($e)
	}

	// Show a nice message to the user instead of a 500 page
	return redirect()->with('message', 'Whoops! Something broke :( Sorry, try again later!')
}
```

other errors that Laravel throws out-of-the-box like invalid route are catched since for example invalid routes throw exceptions, and those are not caught and thus handled and thus end up here. However, Laravel does ignore using the `shouldReport` check a few that are usually very noisy and you might not want to have in your logs: https://github.com/laravel/framework/blob/9cc2622a9122f5108a694856055c13db8a5f80dc/src/Illuminate/Foundation/Exceptions/Handler.php#L80-L94.

I hope this answers your question, that it does capture any uncaught errors also those thrown by Laravel (except those in the don't report array, by default) and if you need to capture a caught exception you can also do that.

**Comment by pokono** [comment]
Remember that if you're using laravel you can still `report` catched exceptions.

```
try {

} catch (Exception $exception) {
    report(exception);
}
```

This would be fire the report method and send it to Sentry.

**Comment by stayallive** [comment]
Thanks @pokono, that is also correct. For the lack of response on this issue (and I think it being answered) I'm going to close it, feel free to reopen it in the future if needed.

**Comment by ruedigerm-playster** [comment]
Thanks for the clarifications
