### ISSUE TITLE
ERROR: filemtime(): stat failed for /var/app/storage/framework/views/*.php

### ISSUE THREAD

**Issue by jpswade** [getsentry/sentry-laravel#401]
Hi there,

We get this error quite often, it looks like this:

`ERROR: filemtime(): stat failed for /var/app/storage/framework/views/8ce1a737e6a46ac01a29b32abd3ca9bf1ff8076b.php`

It happens at different times, usually during a deployment when `view:cache` has been run.

The trace usually points to the same thing:

```
#5 /var/app/current/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/var/app/curren...', Array)
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/View/View.php(139): Sentry\\Laravel\\Tracing\\ViewEngineDecorator->get('/var/app/curren...', Array)
```

Here's another example:

```
ErrorException: filemtime(): stat failed for /var/app/storage/framework/views/206a6f3b42468d01ba812891bff8f8025d3eb356.php
#93 /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(375): Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
#92 [internal](0): filemtime
#91 /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(375): Illuminate\Filesystem\Filesystem::lastModified
#90 /vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php(72): Illuminate\View\Compilers\Compiler::isExpired
#89 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(50): Illuminate\View\Engines\CompilerEngine::get
#88 /vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Facade\Ignition\Views\Engines\CompilerEngine::get
#87 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Sentry\Laravel\Tracing\ViewEngineDecorator::get
#86 /vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\View::getContents
#85 /vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View::renderContents
#84 /vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View::render
#83 /var/app/storage/framework/views/e4c890f22d19a62c381a6f4e22403299ee101119.php(30): include
#82 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\PhpEngine::evaluatePath
#81 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\View\Engines\CompilerEngine::get
#80 /vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Facade\Ignition\Views\Engines\CompilerEngine::get
#79 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Sentry\Laravel\Tracing\ViewEngineDecorator::get
#78 /vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\View::getContents
#77 /vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View::renderContents
#76 /vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View::render
#75 /var/app/storage/framework/views/8dc0e3bfef5cf76c16823e3a8fa79458786768c3.php(12): include
#74 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\PhpEngine::evaluatePath
#73 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\View\Engines\CompilerEngine::get
#72 /vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Facade\Ignition\Views\Engines\CompilerEngine::get
#71 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Sentry\Laravel\Tracing\ViewEngineDecorator::get
#70 /vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\View::getContents
#69 /vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View::renderContents
#68 /vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View::render
#67 /var/app/storage/framework/views/57301ad502a7bc380ee7111f9b80913ff782b1d3.php(27): include
#66 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\PhpEngine::evaluatePath
#65 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\View\Engines\CompilerEngine::get
#64 /vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Facade\Ignition\Views\Engines\CompilerEngine::get
#63 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Sentry\Laravel\Tracing\ViewEngineDecorator::get
#62 /vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\View\View::getContents
#61 /vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View::renderContents
#60 /vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View::render
#59 /vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\Http\Response::setContent
#58 /vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\Http\Response::__construct
#57 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(759): Illuminate\Routing\Router::toResponse
#56 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(731): Illuminate\Routing\Router::prepareResponse
#55 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
```

It seems like we're not the only ones to experience this issue, also see:

- https://github.com/laravel/framework/issues/28228#issue-433620914
- https://forum.sentry.io/t/ability-to-ignore-issues-with-matching-exception-message/2009

We've been trying to get to the bottom of this issue for a few weeks now, but despite removing Scout APM and upgrading Sentry Laravel package to latest, the issue still persists.

**Comment by stayallive** [comment]
Hi @jpswade are you using a zero downtime deployment tool like envoyer.io or Deployer? And may I ask what version of Laravel you are using

This is a quite common occurence when deploying because of a race condition in the view engine when the symlink to your deployment is updated.

This is _not_ caused by Sentry, we decorate the view engine and that is where the stacktrace comes through but if you look a little closer you see more engines:

```
#92 [internal](0): filemtime
#91 /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(375): Illuminate\Filesystem\Filesystem::lastModified
#90 /vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php(72): Illuminate\View\Compilers\Compiler::isExpired
#89 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(50): Illuminate\View\Engines\CompilerEngine::get
#88 /vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Facade\Ignition\Views\Engines\CompilerEngine::get
#87 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(47): Sentry\Laravel\Tracing\ViewEngineDecorator::get
```

Ours is there (87) and the decorator from Ignition is in there (88) and eventually the `CompilerEngine` from Laravel (89) which tries to figure out if the file was last modified and causes that warning.

You could ignore this warning either in Sentry itself or in your code by using the [`before_send`](https://docs.sentry.io/platforms/php/configuration/filtering/#using-beforesend) option and inspecting the event.

**Comment by jpswade** [comment]
Hi @stayallive thanks for getting back to me.

Yes, we're using AWS elasticbeanstalk, you'll find the Laravel specific documentation here:

* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-laravel-tutorial.html

As far as I'm aware, facade/ignition became the default error page handler for all Laravel 6 applications and above, so it would seem odd if that was the issue. I'll upgrade facade/ignition to see if that brings any joy. If not, then I'll also report it to them.

My reasoning for believing this package is at the heart of the problem is mainly due to this thread:

* https://github.com/laravel/framework/issues/28228#issuecomment-577374469

**Comment by stayallive** [comment]
I think you misunderstood, I was trying to explain just because we (and others) are in the stacktrace the problem does not come from us. They also don't come from Ignition. 

This is a race condition in the Laravel view engine when you deploy a user accesses the application and exactly when Laravel tries to find some things out about a cached view the new deployment is promoted which causes the cached view to "disappear" either because of the new symlink or the "view:cache" artisan action. This warning is no big deal, it's caught and the view gets rendered but the warning is raised and you get a alert. 

As far as I know this is just the nature of how the check is and is very hard to solve with how most deployments are done and this warning can be safely ignored (I explained you can use Sentry muting option or the `before_send` hook in your code).

**Comment by jpswade** [comment]
@stayallive sure, I understand the theory, but I'm not convinced.

Bear in mind that this is an error not a warning. My concern is that users will be receiving an error 500 message.

I agree that it is likely related to the fact that we issue a `view:cache` command during deployment, but I'm not fully convinced this is the problem, because the server being deployed to doesn't get put into the load balancer before this command has been run, so it's not realistically possible or at least very unlikely.

As I said, this is not something that we can really ignore as it will likely have an impact on the user experience.

My gut feeling is that there's some kind of issue and sentry is trying to catch this error further up, it's then trying to render an error page and this is when we're getting the error. 

My theory is what we're seeing is an error with Sentry handling the error, which is why we're also seeing ignite in the trace, because it's during the moment it's trying to display the error page, and I think could be masking the original issue.

**Comment by stayallive** [comment]
I am not to familiar with Elastic beanstalk so I'm sorry if I'm making wrong assumptions, but I assumed it worked like Envoyer but because you mention a node being put in the load balancer it sounds like a new EC2 instance is created for each version. If that is true it should not be a race condition like I'm seeing (this error also occurs in some of my apps, especially those with remote storage like a NFS share) but something else entirely. But since were here in the Sentry repo I like to not drift to much and I like to prove to you that we are not causing this error in any way shape or form 😄 

---

> My gut feeling is that there's some kind of issue and sentry is trying to catch this error further up, it's then trying to render an error page and this is when we're getting the error.

Let's not work with gut feelings but with facts, let's prove this! 

> My theory is what we're seeing is an error with Sentry handling the error, which is why we're also seeing ignite in the trace, because it's during the moment it's trying to display the error page, and I think could be masking the original issue.

I have a way for me to prove to you it is not Sentry I believe, let me explain:

The only Sentry class in the stacktrace is `Sentry/Laravel/Tracing/ViewEngineDecorator`, this is part of our tracing ([performance monitoring](https://sentry.io/for/performance/)) and not our error tracking. We enable this because we can't know when or if a trace is needed (to explain why it's even there while you might not be using any performance monitoring features).

In your `composer.json` add (or merge with existing) the following config (this opts out of automatically registering Sentry):

```json
    "extra": {
        "laravel": {
            "dont-discover": [
                "sentry/sentry-laravel"
            ]
        }
    },
```

After running `php artisan package:discover` (in my case I needed to it twice...) there is no longer the line:

```
Discovered Package: sentry/sentry-laravel
```

And then add to your `config/app.php` in the `providers` array the following service provider: `\Sentry\Laravel\ServiceProvider::class`.

You can validate `php artisan sentry:test` still works after you've done this to know Sentry is still active just not it's performance monitoring service provider.

What you've done is completely disable our performance tracing code, which the `Sentry/Laravel/Tracing/ViewEngineDecorator` is a part of. You left error tracking working exactly as before.

Now, I know there is not a good way of "triggering" this error/warning to occur (I noticed too sometimes it's an error, sometimes a warning) but you'll have to wait for it to happen again and you will say it still does but this time without any `Sentry\*` file in your stacktrace. 

This way I hope I can prove to you that this is not caused by Sentry, this is just the way we implemented our tracing for views and we're just there for the ride in the stacktrace. 

Check out the [decorator](https://github.com/getsentry/sentry-laravel/blob/584c90498bf38dd98e2604fb5fc0336beb23bfad/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php) code too, it's very simple and doesn't do much except Sentry things and passing everything through to the actual view engine).

I hope you are willing to try the above so we can rule out Sentry (I believe it will), and please keep me updated and/or ask any follow up question if I need to explain something more in depth or differently.

**Comment by jpswade** [comment]
I've made a few changes:
1. I've applied the above suggestion to remove Sentry Performance Monitoring.
2. I've upgraded Facade\Ignition
3. We now use `view:clear` at pre-deploy time
4. Facade\Ignition is now disabled by default

We'd like to try out the Sentry Performance Monitoring at some point in the near future, so we might undo your suggestion if we see no further blips after a few days, that'll also have the side benefit as to see if the issue stays gone.

I'm now thinking that, certainly this last issue anyway was because Facade\Ignition was enabled when it wasn't meant to be.

Thanks for your help.

**Comment by stayallive** [comment]
The interesting bit would be `3` I think, you used to do it after deployment went live?

Anyway, I hope it works and I hope my story properly explains what we do and how we do it and convinces you this error is not generated by the Sentry Laravel integration and if it doesn't happen again you should be safe to undo the changes I suggest (and also if it does happen again when you no longer see Sentry bits in the stacktrace).

Let me know how it goes 👍

**Comment by jpswade** [comment]
Just a bit of insight, the way elasticbeanstalk deployment works is how you'd expect:

- Takes the server out of the LB
- Pre deploy hooks run
- Deployment occurs
- Post deploy hooks run
- Server gets put back into LB

In theory, adding `view:clear` to the pre-deploy shouldn't make any difference, because we ran `view:cache` once the new code was deployed post deployment anyway, before it got added back into the load balancer. We've got to the point where we're willing to give anything a go if we think it might help, so it's in there as belt and braces.

Thanks for the story, I hadn't yet got around to digging into that level of the Sentry package yet, so it was good to be able to run this thread in parallel and cancel it out as a possibility.

I'll let you know how it goes.

**Comment by jpswade** [comment]
Well, since doing the changes, we've not seen a repeat of this issue, so it could be any of the changes or perhaps a combination, resulting in a bit of a perfect storm.

We're going to turn "Sentry Performance Monitoring" back on and see if the problem returns, if not, then I think we're done here.

**Comment by stayallive** [comment]
Sounds great! Happy to hear at least the problem seems to be resolved.

Let's hope it indeed doesn't return!

**Comment by stayallive** [comment]
So I assume this was probably fixed or resolved since I've not heard back anymore 👍 

I'm closing the issue feel free to re-open if there is still things to look into!
