### ISSUE TITLE
Customize sentry transaction name

### ISSUE THREAD

**Issue by illambo** [getsentry/sentry-laravel#415]
## Versions:
- PHP Version: 7.4.12
- laravel/framework: 8.14.0
- sentry/sentry: 3.0.4
- sentry/sentry-laravel: 2.2.0

## Question:
Hello, I am looking for a little help to configure (rename) the transaction name for Sentry.
I think it is useful for performance tracking tool, I need customize transaction name because I have a unique graphql endpoint so depending on `request()->input('operationName')` or `request()->header('x-apollo-operation-name')` 
I would like to customize the transaction name.

I can tag the request but I haven't found a way to rename it yet.

```php
\Sentry\Laravel\Integration::configureScope(function (\Sentry\State\Scope $scope): void {
    //$scope->setExtra('character.name', 'Mighty Fighter');
    //$scope->setTag('example-tag', 'pippo');
});
```

I try with this, but maybe Sentry terminate middleware override the transaction name:
```php
\Sentry\configureScope(function (Scope $scope): void {
    $scope->getTransaction()->setName('Pippo');
});
```

I also tried with [before_send](https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#hooks) hook but it appears not to be triggered.

Do you have any suggestions for me?
Thanks!

**Comment by stayallive** [comment]
Hi @illambo, this should work for you, `before_send` is the best place for this:

```
    'before_send' => static function (Sentry\Event $event) {
        logger()->debug('Hello from the before_send hook!');

        $event->setTransaction('my-transaction-name');

        return $event;
    },
```

You of course want to modify this a bit to work for your Apollo operation name :)

The reason you think the `before_send` hook is not firing is because the transaction is send after the client response has been send so `dump` doesn't work there. It uses a terminable middleware to achieve this, in the example I've added a debug statement you should find back in your Laravel log so you can see it does fire when it sends a transaction (or "regular" event).

Let me know if this works for you!

**Comment by illambo** [comment]
Thank you so much, it works! I just ran into the mistake you described.

**Comment by illambo** [comment]
With version 2.31 _before_send_ event seems to no longer be raised for "traces sample" case.
Do you have suggestions on how I can rename the transaction in this case or add spans in event ?
Thanks
