### ISSUE TITLE
Unable to install package — requires could not be resolved

### ISSUE THREAD

**Issue by JasonTheAdams** [getsentry/sentry-laravel#430]
Greetings!

Just got signed up with Sentry and tried to install the composer package into our project. I got the following:
```
Using version ^2.3 for sentry/sentry-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/psr7 (locked at 1.6.1) -> satisfiable by guzzlehttp/psr7[1.6.1].
    - sentry/sentry-laravel 2.3.0 requires sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0].
    - sentry/sentry-laravel 2.x-dev requires sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0].
    - Conclusion: don't install sentry/sdk 3.1.0
    - Installation request for sentry/sentry-laravel ^2.3 -> satisfiable by sentry/sentry-laravel[2.3.0, 2.x-dev].

Installation failed, reverting ./composer.json to its original content.
```
We're on Laravel 7.11 and I don't see any obvious dependency conflicts. Any ideas?

Thanks!

**Comment by stayallive** [comment]
Welcome, and sorry for the initial troubles, let's see if we can iron that out!

We require `guzzlehttp/psr7` of version `^1.7`, the error says composer has it locked at `1.6.1`.

This could mean 2 things, either you have it locked in your own `composer.json` or composer is not thinking about upgrading it, you can try to remove you lock file before requiring Sentry to see if that helps, otherwise could you share you `composer.json` file so I can try and see what's conflicting?

**Comment by JasonTheAdams** [comment]
Weird, I updated a few packages but couldn't quite anything that was specifically preventing `guzzlehttp/psr7` from being updated to `^1.7`. Anyway, it's working not and wasn't Sentry's fault. Thanks for the help!

**Comment by stayallive** [comment]
Great, happy to hear you're up and running 👌
