### ISSUE TITLE
Docs: Add Infomation on how to disable sentry during (unit-) testing.

### ISSUE THREAD

**Issue by TylerFiekens** [getsentry/sentry-laravel#435]
Hello,

I'd like to make a proposal for a documentation enhancement; During the initial installation process there should be a section dedicated on how to disable sentry while running unit tests.

Following your instructions, the `Sentry\Laravel\Tracing\Middleware` will be globally loaded by the `SentryServiceProvider` this loading results in really slow Unit Tests. On my local machine this middleware took almost 4 seconds to terminate. This will obviously not happen if the sentry DSN isn't set. 

I propose the following addiction to the on boarding process;

The Sentry service provider should only be loaded when the application is in production mode. For that we need to tell Laravel not to autoload the SentryServiceProvider within the `composer.json`.

```json
"extra": {
      "laravel": {
          "dont-discover": [
              "sentry/sentry-laravel"
          ]
      }
  },
```

Now the user has full control of how and when the ServiceProvider will be loaded. The most common use of this would be in the `App\Providers\AppServiceProvider`. Using the boot method we can register the ServiceProvider manually when the application is in production mode.
```php
if (! $this->app->isLocal()) {
    $this->app->register(\Sentry\Laravel\ServiceProvider::class);
}
```

I think this would avoid potential issues or confusions.

If there are any questions you might have feel free to reach out. Thank you.

**Comment by stayallive** [comment]
Hi @TylerFiekens, 

It [is recommended](https://docs.sentry.io/platforms/php/guides/laravel/#local-development) to not have a DSN set or have it set to `null` locally and when running unit tests. Setting the `DSN` to `null` will prevent the library from registering events and should effectively do nothing.

Is there a specific reason why you'd want to not load it at all when running unit tests?

**Comment by TylerFiekens** [comment]
Hey @stayallive,

thank you for your question. As I described in my initial comment I was very confused why my e2e tests were running very slow (like 4 seconds for each test slow). This was because the tracing middleware was loaded globally by the Service Provider. This could be resolved by either using my method of loading the Service Provider manually, or by setting the sentry DSN to `null` as you described. Either way, this may be confusing for users because it is not that intuitive to see what my cause the slowdown. It would be great if we could either extend the documentation to explicitly warn users of this potential issue.

**Comment by stayallive** [comment]
I feel like we documented this halfway:

- https://docs.sentry.io/platforms/php/guides/laravel/#local-development (general)
- https://docs.sentry.io/platforms/php/guides/laravel/performance/#improve-response-time

We could expand on that to mention tests of course in case that was not clear. And expand that the terminable middleware solution we use does not work for tests. 

But again, Sentry should not be enabled and have a DSN set when running tests so that should be the main focus of any change. 

But what I really want to know is if when setting the DSN to `null` it "fixes" the 4 second e2e tests you are seeing? You can of course also disable tracing by setting the `traces_sample_rate` to `0` which should have the same effect if for some reason you need Sentry in your tests. 

If so I'll see if we can expand the docs to explicitly mention to not set a DSN when running tests.

**Comment by TylerFiekens** [comment]
Yes, not setting a DSN will fix the problem with my e2e tests. I was locally testing if an event would be send to sentry before a deployment, that is why I had it set (and I forgot to unset it.).  I don't think, as you said, that there is no reason to enable sentry tracing for unit tests.

Then again, seen as I am the only person to seems to have run into the "problem", one could argue that an extension is not necessary, It just be neat to inform about this potential "issue" because I did not find anything at the time. Maybe this Issue would be enough if anyone run into this problem.
