### ISSUE TITLE
how can i download the file with errors laravel?

### ISSUE THREAD

**Issue by PartosK** [getsentry/sentry-laravel#445]
Can you please tell me I have a file with error logs that occurred before I connected the project, can I download it somehow?

**Comment by stayallive** [comment]
I am sorry, I am not sure what you are asking?

If you added Sentry at some point all error logs before that point but also after that are still where they were and are still being written too. Sentry does not change anything about what is written to the error log so that is still working with Sentry enabled too.

Laravel usually keeps error logs in `storage/logs` so what you are looking for might be in there?

**Comment by PartosK** [comment]
@stayallive the files have not disappeared anywhere, they are, I mean, is it possible to load those errors from them that were previously in order to analyze.

**Comment by stayallive** [comment]
Ahh, I see!

No that won't be possible, or useful since most extra information Sentry collects would not be in those logs. But regardless it's not possible to "import" from existing error logs.
