### ISSUE TITLE
Sentry - sentry.php SENTRY_ENVIRONMENT config

### ISSUE THREAD

**Issue by brifiction** [getsentry/sentry-laravel#446]
Hi Sentry team,

I would like to point out that `SENTRY_ENVIRONMENT` value is not defaulting to Laravel's `APP_ENV` below (if left empty). It should look like 'dsn' line (sort of - it is defaulting to non-Laravel env config).

```
...
...
return [

    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),
    ...
    ...

    // When left empty or `null` the Laravel environment will be used
    'environment' => env('SENTRY_ENVIRONMENT'),

...
...
```

Please feel free to correct above, as perhaps the comment for 'environment' is old? Or did Laravel change their `APP_ENV` to something else recently? 

Thank you!

**Comment by stayallive** [comment]
Does it actually not work or do you think it won't work because of the missing default value?

As stated it needs to be left empty or `null` for this code to take over and get the environment from the Laravel application instance: https://github.com/getsentry/sentry-laravel/blob/be9658a57d554f8bfe587facc1492a45c6bd0e1c/src/Sentry/Laravel/ServiceProvider.php#L131-L134.

If you could tell me what version of Laravel and the Sentry Laravel SDK you are running I'd be happy to investigate if you are seeing it actually not working as expected.

**Comment by brifiction** [comment]
Thank you @stayallive for replying and sharing above. At this point, I believe I misread the 'the Laravel environment will be used' code comment, based on now viewing the `ServiceProvider.php` file above. We initially thought it was only related to the `APP_ENV` field in the `.env`. 

Either way, I'm glad that the above 'code block' is declared, as I believe it is a 'future-proof fallback approach' for Laravel.

To answer your question, we're currently on:
1. Laravel is v7.28.4
2. `sentry/sentry-laravel` is v2.3.1.
