### ISSUE TITLE
Is it possible to send tracing in async mode?

### ISSUE THREAD

**Issue by mix5003** [getsentry/sentry-laravel#450]
is it possible for send tracing in async mode? 
i think it make sense to send error in sync mode. 
but i think it not for tracing. it would  be nice if it can send in async mode or in queue.

**Comment by stayallive** [comment]
Hi @mix5003 there is no async mode (because php has no real async capabilities) but the tracing information is sent after the response your app generates is sent using a terminable middleware. So if you are using php-fpm tracing should have no impact on the response times. 

We have also some docs on how to use Relay to further minimize the impact on your application: https://docs.sentry.io/platforms/php/performance/#improve-response-time. 

I'm guessing you are here because you observed slower response times after enabling tracing? Could you share a bit more information about your setup so we can see if there is anything else other than the above we can do?

**Comment by mix5003** [comment]
i am deploy on docker images ` php:7.4.13-apache` . 
but i think sometime my network connection has a problem, so i want to send to queue or somewhere in my local network first.

i think Relay is what i looking for. 
thank you for your answer.

**Comment by stayallive** [comment]
That sounds like relay would be a perfect fit for you 👌
