### ISSUE TITLE
Use Laravel queue to send events to Sentry

### ISSUE THREAD

**Issue by mnbp1371** [getsentry/sentry-laravel#452]
When I run the  `app('sentry')->captureException($error);` , the speed of the program is very slow. i think you need to job in laravel or lumen.But this has many problems، for example: exception can not be serialize

**Comment by stayallive** [comment]
You don't give a lot of information about your setup so I'm going to make a few assumptions.

Do you have tracing enabled with `traces_sample_rate` set to anything higher than `0`?

Otherwise we have chosen this behaviour by design. When you send an event to sentry.io we expected there to be something wrong and you want to make sure that event comes to Sentry so we can let you know, and in PHP this comes at the cost of the response time (but again most requests to your app should not have to sent anything to Sentry so it's only the requests where something is going wrong).

PHP has no way to do async stuff and we could possibly leverage the queue but that also doesn't guarantee to work if your app is having trouble so that brings a whole host of other cases where events never reach sentry.io.

We have a solution though it's a bit more involved than just flipping a switch in the config 😄 

It's called [Relay](https://docs.sentry.io/product/relay/getting-started/) and it's used to relay events you send to it forward to sentry.io. This will probably solve any performance issues you are seeing. This explains it pretty well how it works (this is in the context of our performance features but works the same for `captureException`, it all goes through relay if you configure it that way): https://docs.sentry.io/platforms/php/performance/#improve-response-time

> Because of the nature of PHP, requests in most cases are sent in the same process as you serve your users' response. In sum, this process affects the time it takes to send a request to Sentry, as it is added on top of your servers' response time. To mitigate this and reduce the addition close to zero, you can use a Relay running locally on the same machine or local network that acts as a proxy/agent. As a result, instead of your PHP process sending things to Sentry, the PHP process sends it to your local Relay, which then forwards it to Sentry.

**Comment by robsontenorio** [comment]
@stayallive  how about the new `::dispatchAfterResponse()` ?

https://laravel.com/docs/8.x/queues#dispatching-after-the-response-is-sent-to-browser

**Comment by stayallive** [comment]
Hi @robsontenorio, `dispatchAfterResponse` is using the exact same logic as a terminable middleware so that won't help unfortunately. But I need to know a bit more since sending traces (https://sentry.io/for/performance/) to Sentry and sending exceptions to Sentry are handled differently and I don't know which one you are referring to at the moment.

Are we talking about tracing causing slower responses or are we talking about events being sent to Sentry (such as exceptions or log messages)? 

What web server software are you using and are you using PHP-FPM?

**Comment by robsontenorio** [comment]
@stayallive i am talking about sending exceptions to Sentry. Yes I am using php-fpm. 

I will dig sentry package. But on  my recent project just tested  “dispatchAfterResponse” and worked perfectly as excepted calling an external API without lag.

**Comment by joriswvanrijn** [comment]
Is there any progress on this feature request? Would love to do the same!

**Comment by Fossil01** [comment]
Is there any progress on this?

**Comment by jiaconcon** [comment]
I have the same problem

**Comment by loranger** [comment]
Would love a queued error tracking too, in order to speed up error rendering

**Comment by robsontenorio** [comment]
At this moment "dispatchAfterResponse" approach to handle is not an option?

> @stayallive i am talking about sending exceptions to Sentry. Yes I am using php-fpm with Nginx.
> 
> I will dig sentry package. But on my recent project just tested “dispatchAfterResponse” and worked perfectly as excepted calling an external API without lag.

Is that a not valid approach to improve Sentry sending exceptions?

**Comment by d8vjork** [comment]
Now that Sentry is suffering from an outage, we're having big problems on our application response time

For these cases, a PR with this makes much more sense

![image](https://user-images.githubusercontent.com/2331052/167173707-9cdf93fd-3623-4317-8b26-000a7265abed.png)

**Comment by zhaozhenxiang** [comment]
Hi.
I also need to put the send request in the queue for execution.

**Comment by zhaozhenxiang** [comment]
> Hi. I also need to put the send request in the queue for execution.

![未命名文件(3)](https://user-images.githubusercontent.com/11980681/171560936-e33f9f32-c9a2-44f0-aaa9-d3c0985ccf7e.png)
This is my temporary solution.

**Comment by cleptric** [comment]
While I agree that, at least in the context of performance monitoring, utilizing a queueing system might be a great idea to reduce overhead, we also have to take applications into account that do not use such queues.

Sentry already provides a great solution to minimize the mentioned performance overhead, which we call a local Relay (sidecar). https://docs.sentry.io/platforms/php/guides/laravel/performance/#improve-response-time

The binary has no dependencies and should work on almost every OS you might use in production. You can either deploy it side by side with your app or run a centralized instance in your k8s/container environment.
https://github.com/getsentry/relay

Using a local Relay will drastically reduce response time when Sentry is involved, so you should give it a try! Please let us know if you run into any issues.

**Comment by d8vjork** [comment]
So... my only concern about this Relay thing... would this prevent my app to suffer from Sentry platform outages? If so would it retry the events by itself so my PHP app doesn't need to lose data events sent?

Will definitely give a try on our infrastructure

**Comment by antonpirker** [comment]
Yes, relay does retry in case the data can not be sent on the first try. See also here for all the configuration you can set in relay: https://docs.sentry.io/product/relay/options/

**Comment by robsontenorio** [comment]
But what is the solution ?

**Comment by cleptric** [comment]
@robsontenorio https://github.com/getsentry/sentry-laravel/issues/452#issuecomment-1237919922

Using a local Relay https://docs.sentry.io/product/relay/

**Comment by summerKK** [comment]
see https://github.com/getsentry/sentry-laravel/issues/792#issuecomment-1815988621
