### ISSUE TITLE
Laravel native Relay

### ISSUE THREAD

**Issue by tillkruss** [getsentry/sentry-laravel#470]
Hi there!

Running a dedicated process for Relay isn't an option for us, but we'd love to leverage performance tracking anyhow without an impact to HTTP requests.

What about creating a Laravel-native solution, for example sending performance (and maybe errors) to the local database and using Laravel Horizon or regular queue to push up the requests every minute?

Is that something you'd like to see as a PR?

**Comment by stayallive** [comment]
Hi @tillkruss, I don't think that is needed for most cases.

We use a terminable middleware for sending the tracing data.

It depends on how you run PHP but at least with PHP-FPM there is no end-user impact of sending the tracing data since the trace is sent to Sentry after the user got it's response.

I'm currently not sure we even can serialize and unserialize the data with the current SDK and send events later... but that would be easy to test out of course. But so far I'm not convinced maintaining a database (and next is probably full queue) implementation is currently a good idea. But happy to discuss it further of course.

**Comment by tillkruss** [comment]
@stayallive That makes perfect sense. I was confused after read this: https://docs.sentry.io/platforms/php/performance/#improve-response-time

**Comment by stayallive** [comment]
Yeah we might want to improve on that to mention how the Laravel and Symfony integrations handle this on PHP-FPM. Although Relay is the recommended solution still, but I understand that that is certainly not possible or practical everywhere.
