### ISSUE TITLE
Feature Request: Artisan command to register a new release

### ISSUE THREAD

**Issue by bilfeldt** [getsentry/sentry-laravel#471]
It would be nice with a new artisan command `sentry:release` which would call the Sentry API and notify Sentry about a new release (as recommended by the [Sentry docs](https://docs.sentry.io/product/releases/setup/release-automation/).

This would be really helpfull for usage in CI/CD tools like Laravel Envoyer.

**Comment by stayallive** [comment]
Hi @bilfeldt,

Yes that would be very nice but we already have great language independent tooling for this: https://docs.sentry.io/product/cli/.

That's we are not going to add an artisan command to create releases and deploys because Sentry CLI handles that like a dream.

The CLI tool is also a single portable binary which should make it easy to use in CI (for example using the docker containers in GitHub Actions) / CD tools like Envoyer (possibly installing it through NPM when running Laravel Mix).

(see also: https://github.com/getsentry/sentry-laravel/issues/190)
