### ISSUE TITLE
Adding support for Laravel Octane?

### ISSUE THREAD

**Issue by sikhlana** [getsentry/sentry-laravel#479]
It looks like if we're running the web server using a long running process mechanism like **Laravel's Octane** or other packages like `spiral/roadrunner-laravel` or `php-pm/php-pm` or `swooletw/laravel-swoole` the events do not get flushed unless the workers are restarted and also cause issues with scoping each individual requests since the cleaning up and flushing of events aren't being called after each request like how it's handled for job queues.

As Laravel now has an official package (currently in public beta), it would be great if Sentry adds this mechanism for HTTP requests as Octane has the potential to go big.

**Comment by stayallive** [comment]
I personally did not had the time to play with Octane and am also a little hesitant considering it's early beta status. But we are for sure going to make sure it plays nice at some point. 

@filakhtov has already identified a problem for long running processes and fixing that (#475) but I can only imagine there is more we want or need to change so we also need to gather specific information on what is happening and what should be happening so we have a clear idea on what needs to be fixed.

---

But tell me a little more since requests should not need to be cleaned and flushed unless you are using an older version of the PHP SDK which means you are also behind on the Sentry Laravel updates.

Or do you mean the scope is not correctly resetted for each request? Because I can imagine that to be true, but events should still be sent/flushed to Sentry server.

---

I'm also accepting PR's for it if you are willing to dig a bit into it yourself.

**Comment by sikhlana** [comment]
@stayallive I have implemented Octane to one of our micro-services in production to test things out. Here's how the transaction looked like before Octane:
![image](https://user-images.githubusercontent.com/1730777/116009648-b9c6e380-a63c-11eb-8ea8-9c03e6b7a8a1.png)

And this is how it looks like in the Octane version:
![image](https://user-images.githubusercontent.com/1730777/116009682-e11db080-a63c-11eb-938f-591cd9a2664e.png)

Basically trace spans of old requests are being included as well as the scopes aren't getting flushed. I guess the main ideology was that `php-fpm` or `mod_php` will create/fork a new process for every request which in turn will create a new scope for that HTTP request and once it's handled the process will be cleared which will trigger the flushing of the event to Sentry. I've just skimmed through the SDK's code so do apologize if I'm wrong.

By **flushing**, I meant calling these two methods:

The one that is being called before every job is processed:
https://github.com/getsentry/sentry-laravel/blob/51f608e83e1a38c379b7a0ac755b461196eefe73/src/Sentry/Laravel/EventHandler.php#L540

The one that is being called after every job is processed:
https://github.com/getsentry/sentry-laravel/blob/51f608e83e1a38c379b7a0ac755b461196eefe73/src/Sentry/Laravel/EventHandler.php#L534

_I believe the same pattern can be implemented for Octane's HTTP server and actually am working on a PR to resolve these issues and should be ready soon._

**Comment by sikhlana** [comment]
@stayallive also, you are right, I was talking about the flushing issue of an old SDK. The events are sent to Sentry as soon as they are triggered with the new SDK.

**Comment by tm1000** [comment]
There are several events for octane. Including events for each "session" so you should be able to attach the listeners written for jobs against the octane events as well

**Comment by tm1000** [comment]
I believe you would link:

- \Laravel\Octane\Events\RequestReceived::class to prepareScopeForQueuedJob
- \Laravel\Octane\Events\RequestTerminated::class to afterQueuedJob

**Comment by tm1000** [comment]
Added support for the Octane events in #495. The events work the same way as Queue events

**Comment by stayallive** [comment]
If your are using Laravel Octane and are here because you need support for it check out #479 and give it a test drive and let us know if there is anything we have to or could improve!
