### ISSUE TITLE
move_uploaded_file causing 500 errors

### ISSUE THREAD

**Issue by raszi** [getsentry/sentry-laravel#486]
### Environment

How do you use Sentry?
self-hosted

Which SDK and version?

sentry/sentry
sentry/sentry-laravel

### Steps to Reproduce

1. Upload a file in an HTTP request
2. Move the uploaded file to a different location with `move_uploaded_file()`
3. Report an issue with Sentry

### Expected Result

The issue is being reported with the request data

### Actual Result

During the request information collecting phase at [`Sentry\Laravel\Http\LaravelRequestFetcher`](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Http/LaravelRequestFetcher.php#L32) the underlying implementation could raise an exception - in our case [`GuzzleHttp\Psr7\Utils`](https://github.com/guzzle/psr7/blob/1.8.2/src/Utils.php#L372-L376) - because the file is not readable anymore.

This unhandled exception will cause a 500 error even when there was no actual error during the request processing.

**Comment by stayallive** [comment]
Hi @raszi, that is not supposed to happen of course.

Do you have these 2 packages installed?

```
composer require symfony/psr-http-message-bridge
composer require nyholm/psr7
```

I'm asking because we try to first use Laravel built-in method to get a PSR-7 request: https://laravel.com/docs/8.x/requests#psr7-requests but fallback to our own method and want to make sure which one of them you are hitting.

My guess is that you do not have those packages installed because that should not hit GuzzleHttp PSR-7 code. My next question would be if it is resolved when you do install those?

We are of course going to fix it either way, but want to make sure we fix it in the right place.

**Comment by mateuszbooste** [comment]
I can confirm the exact problem. After uploading file we are getting 500 error. I just updated sentry laravel to the latest version and issue still occurs.

**Comment by stayallive** [comment]
Was the error not happening before you updated to the latest version? Which version had you installed before?

**Comment by mateuszbooste** [comment]
I think it's not about the package's version. First time I saw this error was after upgrading my Laravel. I have used Laravel 7.24 and I updated to 8.0 without updating laravel sentry package. It was ^2.1.

**Comment by stayallive** [comment]
Makes sense, wanted to confirm it did not start happening because looking at the code this could be happening for quite some time.

**Comment by mateuszbooste** [comment]
Forgot to mention. Now I updated sentry laravel to 2.5.

Because of that I have disabled sentry at the moment. Waiting for the fix. Thank you!

**Comment by stayallive** [comment]
I think we can solve it with #487.

You can try this branch out by changing your `composer.json` and running `composer update`:

```diff
-	"sentry/sentry-laravel": "^2.5"
+   "sentry/sentry-laravel": "dev-fix-uploaded-file-error#b8d030d787e383687bab0fc901d96fbbf6dbb4f3"
```

Let me know if that solves the issue for you!

**Comment by mateuszbooste** [comment]
Amazing. It's working perfectly!

**Comment by stayallive** [comment]
The problem is that we try and construct a PSR-7 (which is a standard) request from the Laravel request, but it tries to gather some information about the uploaded files it can no longer retrieve because the files were moved causing the errors. The PR tries to create that PSR-7 version of the request as soon as possible to make sure all information is still intact.

**Comment by stayallive** [comment]
Should be fixed in version `2.5.2` which was just released, thanks for the reports all!

**Comment by mateuszbooste** [comment]
Thanks for quick response!

**Comment by raszi** [comment]
Thank you very much for the quick turnaround.
