### ISSUE TITLE
EventHint

### ISSUE THREAD

**Issue by drmax24** [getsentry/sentry-laravel#508]
Some time ago it was possible to send EventHint data together with a message string via captureMessage function.
Now i can see that EventHint is commented out and i can't send any extra. Can you allow to send extra again?

**Comment by stayallive** [comment]
To prevent BC the `EventHint` is only commented out on the interface. But the implementation has it so it's safe to use: https://github.com/getsentry/sentry-php/blob/3d733139a3ba2d1d3a8011580e3acf0ba1d0dc9b/src/Client.php#L126-L133.

If you want to be sure you can always check `instance Sentry\Client` before passing the `$eventHint` but this has always been the way how we supported the new `EventHint $hint` param without causing a backwards incompatible change, in the next major Sentry SDK we will of course remove the comment from the interface but for now know what it's commented out because BC but it works just fine 😄  (unless you are using a custom client and have not added that param yourself).
