### ISSUE TITLE
Publish command doesn't publish config/env when successfully sending a test event/transaction

### ISSUE THREAD

**Issue by BenSampo** [getsentry/sentry-laravel#523]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Laravel SDK 2.10.1

### Steps to Reproduce

1. Run `php artisan sentry:publish --dsn={{DSN}}`
2. Answer `yes` to `Enable Performance Monitoring?`
3. Answer `yes` to `Want to send a test event & transaction?`

### Expected Result

The test transaction is sent AND the config is published along with the .env entries.

### Actual Result

Only the test transaction is sent. The config and .env entries only get published when answering `no` to `Want to send a test event & transaction?`

**Comment by stayallive** [comment]
Is there an error when testing your DSN?

The command only makes changes if you choose to test and the test succeeds or don't choose to test. 

So there should have been errors when testing your DSN which is why the values were not set as expected. 

Your changes move the setting values up, but I feel it's more useful to only do anything if the test succeeds to prevent broken values.

**Comment by stayallive** [comment]
Should be fixed now: https://github.com/getsentry/sentry-laravel/releases/tag/2.10.2. 

Thanks for reporting 💪

**Comment by BenSampo** [comment]
Thanks @stayallive 👍
