### ISSUE TITLE
Use $container->call for `traces_sampler`

### ISSUE THREAD

**Issue by pionl** [getsentry/sentry-laravel#536]
👋 all,

It would be great if the `traces_sampler` would not require `static` method but use $container->call to call provided `sample` method in provided class. Why?

- Non static method in class -> we can use `SentryService` convention
- We can use container dependency injection (now we need to use `app`).
- It would be easier to test the "sample" method via PHPUnit test (without Laravel app).

From this code:

```php
class SentryService
{
    /**
     * Sample method required by Sentry SDK.
     *
     * @param SamplingContext $context
     *
     * @return float
     * @throws BindingResolutionException
     */
    public static function sample(SamplingContext $context): float
    {
        $app = app();
        /** @var Guard $guard */
        $guard = $app->make(Guard::class);;
        /** @var Request $request */
        $request = $app->make(Request::class);

        if ($context->getParentSampled()) {
            // If the parent transaction (for example a JavaScript front-end)
            // is sampled, also sample the current transaction
            return 1.0;
        }

        if ($guard->check() === false) {
            return 0.0;
        }

        if ($request->cookie('performance', false) !== false) {
            return 1.0;
        }

        return 0.1;
    }
}
```

to this code

```php
class SentryService
{
    /**
     * Sample method required by Sentry SDK.
     *
     * @param SamplingContext $context
     * @param Guard           $guard
     * @param Request         $request
     *
     * @return float
     */
    public static function sample(SamplingContext $context, Guard $guard, Request $request): float
    {
        if ($context->getParentSampled()) {
            // If the parent transaction (for example a JavaScript front-end)
            // is sampled, also sample the current transaction
            return 1.0;
        }

        if ($guard->check() === false) {
            return 0.0;
        }

        if ($request->cookie('performance', false) !== false) {
            return 1.0;
        }

        return 0.1;
    }
}
```

Thank you for considering. If needed, I can make PR.

Have a great day,

**Comment by stayallive** [comment]
I might be missing something here but you still have a `static` method in your `SentryService` now right? 😄  
But I think I get what you intended 👍 

There is currently no special handling for the `traces_sampler` config option, it's handled by the underlying SDK so I'm not sure we can (without breaking existing code) override that and let the Laravel container handle it, maybe it is as simple as wrapping the option in a callback ourselfs using the container but give me some time to think about this and the effect it might have, otherwise it might have to wait for a next major version which I'd rather not do.

**Comment by pionl** [comment]
Hi, thanks for answering. It should not be a problem.

The syntax is same, but you can do something like this. I could probably make PR. I would do this:


```php

$sampler = $this->config---;


if (is_array($sampler)) {
     $class =  $sampler[0];
     $method = $sampler[1];

    $container = app(); // or better, inject Container contract or $this->app in container

    // static method exits
    if (method_exists($class, $method) === true) {
         $classOrObject = $class;
    } else {
       $classOrObject = $container->make($classOrObject);
    }

   // Laravel will raise exception if does not exist - it is desired because if method does not exits then the sampler is invalid
               $sample = (float) $container->call([$classOrObject, $method]);
}


```

--

Code I've noticed to, at this moment I've disabled javascript tracing. Original I wanted to use current user and check the "user" level but it does not work because sentry is resolved before request (and user) is validated. So I've ended at with a cookie so i cane "start" testing the production env :)

**Comment by stayallive** [comment]
Hey @pionl, if you've already started to look into this you will quickly notice that the code that executes the `traces_sampler` is not part of this repository but part of the base PHP SDK.

So we can in fact not change this code like this because we have no control over it directly 😉 

That's why we would need to proxy the `traces_sampler` (and other callbacks) through a callable of our own that does the `$container->call` method like you said but we cannot simply change the code like you suggested in this repo and also not in the base PHP SDK since it is not Laravel specific.

So there are solutions but want to make sure it has no side-effects because we are changing the passed options and basically proxying them through the container.

**Comment by pionl** [comment]
Sorry @stayallive, probably my mistake not understanding - so we have similar concept. I did not study the code base.

Then if you are OK with it I can make the changes. Thank you for your time

**Comment by stayallive** [comment]
Sure, give it a shot if you can. Otherwise I'll take a look at it later!

Thanks 💪

**Comment by pionl** [comment]
@stayallive Done :)

**Comment by stayallive** [comment]
For now this will not be "fixed", see: https://github.com/getsentry/sentry-laravel/pull/537#issuecomment-1052133354.
