### ISSUE TITLE
How  to notify about long mysql requests ?

### ISSUE THREAD

**Issue by PetroGromovo** [getsentry/sentry-laravel#558]
Using     sentry-laravel 2.12 package in laravel 9 app I wonder if there is a way to catch
long requests(msql,php or javascript side) without run time errors? Say I would like to notify about all mysql requests 
which takes more 10 seconds ?

Thanks in advance!

**Comment by stayallive** [comment]
Sure, you can take some inspiration from our [`EventHandler`](https://github.com/getsentry/sentry-laravel/blob/f647dcf342e78d28e461c2cc88de37f1c89affd7/src/Sentry/Laravel/Tracing/EventHandler.php), for example you can listen to the `QueryExecuted` event and see if the time exceeds a certain limit and use [`\Sentry\captureMessage`](https://docs.sentry.io/platforms/php/usage/#capturing-messages) to send something to Sentry for example.

There is no config setting to do this for you in this package to do this exactly.

You might want to take a look at the performance monitoring features Sentry provides though since you probably can get similar and more info out of that, see: https://docs.sentry.io/platforms/php/guides/laravel/performance/.

**Comment by PetroGromovo** [comment]
Thanks!
