### ISSUE TITLE
Add new SetUserContextMiddleware

### ISSUE THREAD

**Issue by khalyomede** [getsentry/sentry-laravel#567]
Currently, when we enabled "send_default_pii" after the install, the issue have the user id and ip. I propose to add a new optional to use "SetUserContextMiddleware" which will automatically get the authenticated user

- id
- email
- name
- ip

This will help to fill the maximum of available option for the [User context](https://docs.sentry.io/platforms/php/guides/laravel/enriching-events/identify-user/).

In my optinion this middleware should be opt-in (not enabled by default), with some indication where to put the middleware.

I can create a PR for this if you are interested (I've made it for my app, it works fine so far).

**Comment by stayallive** [comment]
I don't see why we would need a special middleware for that? Why can't we extend where we currently extract the user ID (and/or IP) to also get the name and/or email from the model?

The only thing is that there is no standard way to retrieve a name or email from the user model since the attributes are not standard. That's why we initially did not implement this since adding it yourself is really easy as you discovered with your own middleware. 

@cleptric how do you feel about this? We can just try the `name` and `email` field and if the user has any non-standard stuff they can still do it manually as they can now.

**Comment by cleptric** [comment]
Can we actually make sure that the proposed middleware is applied to the queue after the auth middleware? Else we might not have access to the required request attributes.

Given that we already hook into `Illuminate\Auth\Events\Authenticated` and `Laravel\Sanctum\Events\TokenAuthenticated`, we could extend the data passed to the scope and align it with the defaults Laravel provides, so `users.name`  and `users.email`.
