### ISSUE TITLE
Scheduled task monitoring

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-laravel#628]
Sentry has a (in beta since forever) CRON monitoring: https://docs.sentry.io/product/crons/.

It would be really sweet if we can somehow automatically set that up for the user based on their scheduled tasks (basically CRONs): https://laravel.com/docs/9.x/scheduling#defining-schedules.

I'm imagining this requires some sort of synchronize command to be run to talk with Sentry and create the correct CRONs on the Sentry server so depending on how this actually works this might be very easy or tricky or out of scope for the SDK. Will require some investigation but it's an interesting idea!

> As requested by @ankurk91: https://github.com/getsentry/sentry-laravel/issues/625#issuecomment-1362767006.

**Comment by ankurk91** [comment]
Check other similar services

**Comment by cleptric** [comment]
Leaving a link here to a package someone created for the Cron Monitoring feature.

https://github.com/modernmcguire/sentry-cron-monitoring-laravel

**Comment by modernben** [comment]
Thanks @cleptric! Author of that ^ package here. Feel free to borrow as much of the code as you'd like. 

My option is definitely more of an opt-in as it requires the user to add a method to each of their schedules. 

I also played with the idea of a Trait on the job itself with a protected $monitor_id property. I decided against it because I would have to add that to Jobs and Commands and it also wouldn't work for closure based jobs.

Final note if you did want it to be automatic you could use the Events that are fired before/jobs. The hard part would be somehow figuring out the monitor id situation. Maybe use the job name as the unique identifier instead of the monitor id? Not sure if that's a good option as you would have to do a text based lookup on your side then. Sounds expensive to me.

Let me know if you have any questions or want to bounce some ideas back and forth.

Thanks!
Ben

**Comment by cleptric** [comment]
Your approach is a valid starting point. Some sort of auto-setup would be nice, but we have to answer a few open questions on the product first.

**Comment by denisdulici** [comment]
We currently use the `ThenPingMe` service and would like to switch to `Sentry`. They've created the following package for auto-setup:

https://github.com/thenpingme/thenpingme-laravel
