### ISSUE TITLE
Add documentation for context

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-laravel#7]
Refs GH-6

**Comment by Stayallive** [comment]
It would be really nice to have some kind of machanism to add context when a exception is sent to Sentry. I now have a middleware (that goes after the startsession middleware) to set the data since auth data is not available in a serviceprovider' register/boot method I believe (it's to early in the application).

```php
namespace App\Http\Middleware;

use Context;
use Closure;

class SentryContext
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (app()->bound('sentry')) {
            /** @var \Raven_Client $sentry */
            $sentry = app('sentry');

            // Add user context
            if (auth()->check()) {
                $sentry->user_context([...]);
            } else {
                $sentry->user_context(['id' => null]);
            }

            // Add tags context
            $sentry->tags_context([...]);
        }

        return $next($request);
    }
}
```

A [package](https://github.com/rcrowe/Raven/blob/master/src/config/config.php#L55-L86) I used before did it with Monolog processors. This might be a nice way to go about it.

**Comment by dcramer** [comment]
@Stayallive I actually think middleware is a super appropriate place to do this. Gonna toss your example into the docs.
