### ISSUE TITLE
Laravel 9 - sail - transaction not sent

### ISSUE THREAD

**Issue by patricksebastien** [getsentry/sentry-laravel#731]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.6.1

### Steps to reproduce

Laravel 9 using sail (docker) on linux

```
        // sentry custom latency metric monitoring
        $transactionContext = new \Sentry\Tracing\TransactionContext();
        $transactionContext->setName('PSA_loadsheet');
        $transactionContext->setOp('loadsheet');
        $transaction = \Sentry\startTransaction($transactionContext);
        sleep(1);
        // send latency to sentry
        $transaction->finish();
```

I am getting back event ID:

```
...
$transaction = \Sentry\startTransaction($transactionContext);
= Sentry\Tracing\Transaction {#8283}
> $transaction->finish();
= Sentry\EventId {#8274}
```

`.env` is configured and captureMessage / captureException are working.

```
SENTRY_LARAVEL_DSN=https://...ingest.sentry.io/...
SENTRY_TRACES_SAMPLE_RATE=1.0
```

### Expected result

I am not seeing the transaction in Performance interface (All transactions - last hour).

### Actual result

I would like to see the transaction

**Comment by stayallive** [comment]
Can you try and run `php artisan sentry:test --transaction` to make sure the test even and test transaction do come through?

My first hunch is that your transaction has no spans and is thus dropped but I am not a 100% sure on that.

Is there a reason you want to do custom transactions instead of using the automatic transactions and adding your measurement as a span of that transaction?

**Comment by patricksebastien** [comment]
```
DSN discovered from Laravel config or `.env` file!
Sending test event...
Test event sent with ID: 8abb...
Sending transaction...
Transaction sent with ID: 6ccbb...
```

Nothing in `https://....sentry.io/performance/?landingDisplay=all&project=...&query=&statsPeriod=1h`

I can have a look at adding the transaction as a span, but it requires more work AFAIK than using a custom transaction (I need to document myself).

**Comment by stayallive** [comment]
If the `sentry:test` events are not even coming through we can start looking elsewhere first because those really should work. There are 2 things to check. 

Are you over quota? Events are dropped if you’ve already used up all the available performance units and errors. 

Have you tried putting the ID you get back in the search bar? If you empty the search bar completely and enter the ID it should load the error or transaction if it’s available.

**Comment by patricksebastien** [comment]
That's it, we're over quota. It would be nice to add a message about this when running `php artisan sentry:test --transaction`.
