### ISSUE TITLE
Storage Decorator can cause wrong logic to be performed due to overriding the "driver"

### ISSUE THREAD

**Issue by grEvenX** [getsentry/sentry-laravel#775]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

3.8.0

### Steps to reproduce

We're currently using the `spatie/laravel-medialibrary` package together with `sentry-laravel`.
After deploying the latest changes with the new approach to wrapping the disk configuration (introduced in https://github.com/getsentry/sentry-laravel/pull/750) we experienced a problem uploading files to S3.

The changes in the given PR overrides the `config("filesystems.disks.{$this->disk}.driver")` for any given disk to become `sentry`. Any code that relies on checking which driver is being used in this way (through config) now fails to apply it's logic correctly.

Example logic in the Spatie media library where `$diskDriverName` is fetched from the config function above:
```
if (! in_array($diskDriverName, ['s3', 'gcs'], true)) {
  $this->filesystem->disk($diskName)->makeDirectory($directory);
}
```

_PS: It still works in this case, the reason we caught this problem was that we hadn't enabled permission to create directories in S3, so it worked fine when not trying to create a directory but upload the fille "put()" directly._

### Expected result

Enabling tracing on the Storage in a Laravel application should not affect logic

### Actual result

Enabling tracing on the Storage in a Laravel application can potentially affect logic

**Comment by stayallive** [comment]
I'd be happy to hear if anyone thinks of a solution but I don't think there are any in this specific case. I don't know why they are checking the driver name since Flysystem should handle this for you (but again don't know the specifics of this check) without needing to know what underlying system is handling it. 

We went through great lengths documenting the shortcomings of this approach and working around them but we can't code against these assumptions unfortunately and there is no way for us to profile the storage calls without proxying the driver. 

So unless someone has a brainwave or that check is removed from the media library you might have to resort to not enable storage profiling for those disks.

**Comment by grEvenX** [comment]
Yeah, I figured that it was done this way with "good reason". I'm pretty sure as you say that they could handle this differently in the library code, and I will probably raise an issue about it over there.
Just wanted to file this one so at least you are aware.
Haven't looked into the architecture enough yet to see if there's any other ways around this, but I'll shout out if I get time to look deeper into it.
