### ISSUE TITLE
Add more spans outside http.route

### ISSUE THREAD

**Issue by gla23** [getsentry/sentry-laravel#789]
### Problem Statement

I have a badly performing route that has a relatively short http.route and a very long middleware.handle (5 minutes!) I do not know where to look to debug why this is taking so long.

![Screenshot 2023-10-25 at 16 47 45](https://github.com/getsentry/sentry-laravel/assets/15679104/2647688b-8963-4844-83ce-ecaf712abf7d)

### Solution Brainstorm

Things that would be useful:
- Documenting what exactly the current spans are measuring (middleware.handle, http.route and
db.sql.query). I've looked everywhere but can't find anything.
  - As far as I can tell, the "http.route" span is the time taken inside my controller method.
  - Then "middleware.handle" is when Laravel is handling my response. I'm now questioning this because of some debugging I'm doing with the Laravel Debugbar.
  - I thought db.sql.query was adding up the total time it's waiting for SQL to execute, but now I'm not so sure as it's a continuous block rather than a total...
- If there were some spans over the other parts of the Laravel application that are happening in the background that would be amazing for understanding performance issues.

Thanks for the SDK it's super useful!

Sorry if this isn't the best place for this request - it may be I just need a proper debug tool to see everything that's going on.

**Comment by gla23** [comment]
Ah perhaps I should be using the [profiling](https://docs.sentry.io/platforms/php/guides/laravel/profiling/?original_referrer=https%3A%2F%2Fwww.google.com%2F)...

**Comment by stayallive** [comment]
Hey @gla23, we currently do not add spans for each middleware (I also am not sure it's possible currently) to prevent too much span overload since you can have quite a number of middleware, but might be something to explore in the future if it makes sense to add!

The "categories" from your screenshot are the totals of the spans of that type. So the queries of that request took a total of 353ms and can be 1 query but also multiple of course. The `http.route` is indeed your controller and the `http.middleware` is the part after the framework is bootstrapped and before your route action is called so there is definitely something fishy in one of the middlewares.

The best way to dig deeper into this is indeed profiling which should show you which code and/or middleware is active for that long and should give very default insights in the code running!

**Comment by gla23** [comment]
Thanks, that makes sense 😄

Next up I'm struggling to get the profiling to appear. I've updated Sentry to the latest version (23.10.1) but "Profiling" doesn't appear in the sidebar like in the docs. The links aren't there on the Transaction Summary page either. I have verified that my profiles_sample_rate is at 1 (and have sent requests so they should be appearing). I've also checked that `extension_loaded('excimer')` returns true. Is there something I'm missing here? I'm starting to worry that profiling is only available on the Sentry hosted setup but that fact is left out of the docs...

**Comment by cleptric** [comment]
Profiling is available on self-hosted, though I can't offer you any support with this.
You can try our [Discord](https://discord.gg/cWnMQeA), channel `#self-hosted` or drop the team an issue over at https://github.com/getsentry/self-hosted.

As the issue concerning the SDK was hopefully resolved, I'm closing this.
