### ISSUE TITLE
Cron schedule not respection `between`

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-laravel#790]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.8.2

### Steps to reproduce

Similar to: https://github.com/getsentry/sentry-laravel/issues/782

Example setup:
```
$schedule->job(....)
->everyFiveMinutes()
->between('9:00', '18:00')
->countries([Country::TR])
->sentryMonitor('__monitor_slug__')
->onOneServer();
```

### Expected result

Monitor is updated with the crontab: */5 9-17 * * *
"Every 5 minutes, between 09:00 and 17:59"

### Actual result

Monitor is update with crontab: */5 * * * * 
"Every 5 minutes"

Same as the issue linked above, the workaround is to set `updateMonitorConfig:false` and manually config the monitor in the Sentry UI.

<img width="826" alt="Screenshot 2023-11-02 at 10 55 11" src="https://github.com/getsentry/sentry-laravel/assets/64906376/63dc3a9c-bc0d-4327-a742-f1ed29b98c8d">

**Comment by cleptric** [comment]
We'll update the docs, we do not support these types of schedules in Sentry.

**Comment by rodolfoBee** [comment]
Any plans to support it in the future?

**Comment by cleptric** [comment]
This is a question we need to ask the Cron's team cc @gaprl

**Comment by gaprl** [comment]
> This is a question we need to ask the Cron's team cc @gaprl

Hey @cleptric we do support the `*/5 9-18 * * *` expression, the only crontab expression we don't support are six-field ones (for seconds).

**Comment by stayallive** [comment]
We've identified that the problem is also that Laravel currently doesn't expose the information for us to use, so we are unable to know what the `->between` schedule is.

If you are curious that is because Laravel uses a closure to "skip" the execution, so a cron with a `between` schedule is executed in their normal schedule but skipped by a closure outside the range defined in the `between` call. There are no properties on the event where we can extract that information from to properly define a cron schedule. See: https://github.com/laravel/framework/blob/484e9c2c78637e3484681d7569a0e3f878dcd594/src/Illuminate/Console/Scheduling/ManagesFrequencies.php#L23-L71

**Comment by cleptric** [comment]
We clarified our docs in https://github.com/getsentry/sentry-docs/pull/8643

> Tasks that use Laravel's `between`, `unlessBetween`, `when` and `skip` methods are currently not supported.
For the best results, we recommend using Laravel's [`cron`](https://laravel.com/docs/10.x/scheduling#schedule-frequency-options) method to define your schedule's frequency.
