### ISSUE TITLE
Unable to set up sentry sdk debug logger option in Laravel 7

### ISSUE THREAD

**Issue by WinfredPeng2015** [getsentry/sentry-laravel#828]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.8.0

### Steps to reproduce

My enviroment: Laravel 7, PHP 7.4

I am trying to set up the Sentry SDK logger to debug an issue: the performance monitoring is not properly displaying all the API routes on my transactions page.

I am using the Laravel SDK, but the transactions are only showing 4 routes. In my project, there are about 100 routes. I'm not sure where the misconfiguration might have occurred.
My project provides RESTful APIs, so I am only using routes/api.php.

To set up the logger options in Laravel, I followed the Sentry documentation for an option in config/sentry.php named "logger" (https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Fphp%2Fconfiguration%2Foptions%2F%3Foriginal_referrer%3Dhttps%3A%2F%2Fgithub.com%2F#logger). However, this resulted in an error with the older version (3.8.x), indicating that the DebugLogger Classes provided by Sentry did not exist.

Before SDK version 4.0.0, this option only accepted strings. After 4.0.0, the logger option now accepts a Psr\Log\LoggerInterface instance (https://github.com/getsentry/sentry-php/blob/master/CHANGELOG.md#features-2).

After attempting to upgrade the SDK to ^4.1.x, I encountered another error, as shown ![image](https://github.com/getsentry/sentry-laravel/assets/13027416/43e8b4e6-51a6-4e27-b606-8d9b2400509e)

I then realized it was a PHP version issue, so I created a new class extending LoggerInterface. This led to another error related to serialization, as shown 
![image](https://github.com/getsentry/sentry-laravel/assets/13027416/4921ec46-1591-4341-98c2-8e79342f4539)

After having a discussion with sentry support in the discord thread https://discord.com/channels/621778831602221064/1186889992526626866
I tried the approach that official doc provided 
https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/#closures-and-config-caching
and it showed type error.
![image](https://github.com/getsentry/sentry-laravel/assets/13027416/a389c487-bf85-40c4-9bfc-0eadce30b9a2)

### Expected result

The sentry performance monitoring page should show all the api routes in my project.

### Actual result

The sentry performance monitoring page shows only 4 routes.

**Comment by stayallive** [comment]
The logger option is not meant to be used in production and doesn't have any special handling to resolve it from the container or allow it to accept a callable. Maybe it's an idea to when you have the debug logger active not have config caching on? This way you can (temporarily) add the debug logger to your application and see what is going on?

However you have 2 issues here, the first is with the debug logger (which can be solved by using your own implementation of the logger interface for now, we will fix that to work in all PHP versions we support) but the other one is much more interesting.

You mention you are only showing 4 out of about 100 routes, does `php artisan route:list` also show that many routes (I am not a 100% certain Laravel 7 has that command but it's worth a try)?

In addition, how did you configure the sample rate for transactions? Is `tracing_sample_rate` set to `1.0`? Can you maybe share a but more about how you configured those routes that are not showing up?

Did you end up using version 4.x of the Laravel SDK? I want to see if I can reproduce but knowing which version you are currently using will be very helpful and I would strongly recommend to always be using the most up-to-date Laravel SDK supporting your Laravel/PHP version combo (Laravel 7 and PHP 7.4 should be able to run the latest version no problem).

**Comment by WinfredPeng2015** [comment]
> The logger option is not meant to be used in production and doesn't have any special handling to resolve it from the container or allow it to accept a callable.

I am currently using the logger option in my development environment, which is very similar to my production environment.

> Maybe it's an idea to when you have the debug logger active not have config caching on?

Thank you for the suggestion, I will try this approach.

> You mention you are only showing 4 out of about 100 routes, does php artisan route:list also show that many routes (I am not a 100% certain Laravel 7 has that command but it's worth a try)?
The original `php artisan route:list` showed exactly the number that sentry dashboard showed.

The original `php artisan route:list` command shows exactly the same number of routes as displayed on the Sentry dashboard.

I think you have pinpointed the real issue. We are using an API version control package called "dingo-api" (https://github.com/dingo/api). When using this package, routes only appear when using the `php artisan api:routes` command.

I am not sure how to deal with this issue, do you have any suggestions?

**Comment by stayallive** [comment]
I have checked out that package a bit but I can't figure out a event or hook to get the custom router they are using. I'm guessing it's possible but they hi-jack the Laravel router and replace it with their own and do not fire any events and their middleware stack also runs before the route is matched... so I'm a bit at a loss, it also seems like the package is pretty inactive (even the fork) so I'm not sure if it's possible to correctly fix it at this point.

However what you can try is setting `SENTRY_TRACE_MISSING_ROUTES_ENABLED=true` in your `.env` assuming you are using 4.x of the Laravel SDK which might correctly record the routes but might also result in many duplicate routes because parameters are not considered because of the missing route data (so a `/hello/{name}` would normally be recorded but now it might be recorded as `/hello/world` and `/hello/winfred` etc.). Not a perfect solution but maybe good enough for now?

**Comment by WinfredPeng2015** [comment]
I tried the approach for missing routes, and it worked perfectly. Thank you for the tips.

Regarding the dingo-api, I am uncertain about how Sentry captures events. If I extend the `php artisan route:list` command to make my routes appear, would this assist Sentry in capturing the correct routes without the need to set `SENTRY_TRACE_MISSING_ROUTES_ENABLED`?

Additionally, does setting `SENTRY_TRACE_MISSING_ROUTES_ENABLED=true` increase performance quotas and application resource usage?

**Comment by stayallive** [comment]
> Regarding the dingo-api, I am uncertain about how Sentry captures events. If I extend the `php artisan route:list` command to make my routes appear, would this assist Sentry in capturing the correct routes without the need to set `SENTRY_TRACE_MISSING_ROUTES_ENABLED`?

No, that won't help. Sentry listens for the [`RouteMatched`](https://github.com/getsentry/sentry-laravel/blob/debe205d0f9ba4058312a55228ab40401b286e79/src/Sentry/Laravel/Tracing/EventHandler.php#L138-L150) event fired by the Laravel router, dingo-api has a custom setup with their own router and do not fire that event nor set the route on the request (`$request->route()` always seems to be `null`) which is how we detect a route was matched and allow a parameterized transaction name (the `{name}` part of `/hello/{name}`), now you get the raw path from the URL which groups less nicely.

> Additionally, does setting `SENTRY_TRACE_MISSING_ROUTES_ENABLED=true` increase performance quotas and application resource usage?

It increases performance quoatas of course but it won't have much impact unless you have a lot of calls to non-existent routes in your application since those will also be captured, normally we would only capture a transaction if a route exist for it to prevent search engines looking for URLs or hack script looking around consuming transactions. But the impact should be pretty low, but do keep an eye on it of course since its very specific to you and your application how large the impact is :smile:

**Comment by WinfredPeng2015** [comment]
Thank you for the assistance. I will investigate the issue further and try to find a solution myself. Your information has been really helpful.

**Comment by iwex** [comment]
Hello! @stayallive 

> The logger option is not meant to be used in production

As I understand this logger will log errors in sentry plugins.
For example, I tried to debug why sentry is not logging my error on production. Now I know that it is because of payload size > 1mb.

It's good to have a separate file to have sentry logs there (or even send these logs to sentry).
It's bad practice to have some objects in the config.
What do you think about adding 'logger' config parameter as class name (string) and then create it via DI?

**Comment by iwex** [comment]
Also trying to fix it here
https://github.com/getsentry/sentry-php/pull/1722

**Comment by stayallive** [comment]
We can certainly look into getting the logger from the container at some point. If you need it today you can decorate the client builder and set the logger directly: https://docs.sentry.io/platforms/php/guides/laravel/usage/#decorating-the-client-builder. Please open up a new issue for this if you want.

The reason these errors cannot be transmitted to Sentry is because you can easily get into a situation where you get an loop of error sending causing errors to be sent causing errors to be sent etc. So that's a no-go unfortunately 😄

**Comment by iwex** [comment]
> where you get an loop

forgot to say that it was joke :)

**Comment by iwex** [comment]
I've added this to my ServiceProvider
```php
$this->app->extend(ClientBuilder::class, function (ClientBuilder $clientBuilder) {
            $clientBuilder->setLogger(new InternalSentryLogger);
            return $clientBuilder;
        });
```
