### ISSUE TITLE
Dependency nyholm/psr7 can be defined like require-dev

### ISSUE THREAD

**Issue by h4kuna** [getsentry/sentry-laravel#868]
### Problem Statement

I want to remove nyholm/psr7 from my project, if I search for dependencies, composer shows me sentry. Out of curiosity, I looked to see what it was used for. It is now only used in tests. 

### Solution Brainstorm

It will probably be necessary to add dependencies on PSR and describe in the documentation what to download (guzzle, nyholm, symfony). And add info to [suggest](https://getcomposer.org/doc/04-schema.md#suggest).

```json
"require": {
  "psr/http-message": "^1.1 | ^2.0",
  "psr/http-factory": "^1.0"
},
"require-dev": {
  "nyholm/psr7": "^1.0"
}
```

**Comment by stayallive** [comment]
The requirement is required by us because it's required by Laravel to obtain a PSR request object. That's why we have it required because we need a PSR version of the request object.

So your proposed solution will not work unfortunately since Laravel requires the Nyholm package to conjur the PSR request object!

See: https://github.com/laravel/framework/blob/08acc925f1ec8e1c41a54774a36720f506c5b5a8/src/Illuminate/Routing/RoutingServiceProvider.php#L127-L154

**Comment by brc-dd** [comment]
> So your proposed solution will not work unfortunately since Laravel requires the Nyholm package to conjur the PSR request object!

The requirement was removed from Laravel 11. (https://github.com/laravel/framework/pull/53711) It now supports auto-discovery of PSR-17 implementations using https://github.com/php-http/discovery.

**Comment by cleptric** [comment]
We support Laravel 6 and up.

**Comment by brc-dd** [comment]
> We support Laravel 6 and up.

Ah, ok. It's fine though, since `nyholm/psr7` code is not exactly used in the Sentry sdk, it will be there in installed packages but not used if someone has configured `psr/http-factory-implementation` to something else. 👍
