### ISSUE TITLE
Wrong stack trace when using in-app middleware

### ISSUE THREAD

**Issue by webard** [getsentry/sentry-laravel#875]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.4.0

### Steps to reproduce

1. Create middleware that just exists and do nothing
```php
final class DummyMiddleware
{
    public function handle(Request $request, Closure $next): mixed
    {
        return $next($request);
    }
}
```
3. Register it in app.php (L11):
```php
return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        api: __DIR__ . '/../routes/api.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->append(\App\Http\Middleware\DummyMiddleware::class);
});
...
```
4. Trigger any error

This problem happens on Laravel 10 too.

### Expected result

<img width="1198" alt="image" src="https://github.com/getsentry/sentry-laravel/assets/855788/bfcad2a9-a273-4ead-b7db-2d114e7023b7">

### Actual result

<img width="1219" alt="image" src="https://github.com/getsentry/sentry-laravel/assets/855788/b563a466-6cc0-423b-ac94-955d3954958e">

full stack trace is wrong too:
<img width="1218" alt="image" src="https://github.com/getsentry/sentry-laravel/assets/855788/e3cd1898-80dc-4491-ba74-a59f64d7d939">

**Comment by stayallive** [comment]
This is probably because the exception is caused by framework code and not triggered by your own. You are showing an example for a relation not found error triggered by Eloquent, it's really hard to know why or what is actually triggering the error from your screenshots though.

By default we mark only code in your `app` folder as "in app". This causes the stacktrace in Sentry to be collapsed and only frames from your application code are highlighted unless you open the full stack trace. 

So the stack trace is "correct", but for some errors no code from your own application is triggering the actual error causing these kind of stack traces.

Anyway, I'm not sure it makes sense what I am saying but the stack trace is correct, it's just a little confusing in this specific instance.

**Comment by webard** [comment]
Stack trace is correct on both screens, but in "Expected result" is more accurate. In this case, Laravel Nova used relation that does not exist, so actually no app code was executed. 

In cases like that, Sentry indicates on first in-app code that was included in stack-trace and in most cases it will be Middleware, because they participate in every requests.

This can be confusing, but, as I think now, probably there is no better method. Maybe middlewares should not be "Most relevant" if they are not causing error directly?

I'm also not sure if it's the responsibility of this package.

**Comment by stayallive** [comment]
Yeah I totally get what you are saying. I'm not sure there is a good way for us to solve this though. I understand the "Most Relevant" here is misleading but it's also not because of the way middlewares work and your code is usually the most relevant... 

Maybe we should exclude middlewares as in-app frames although currently I don't think that is very easy to do. This is because `in_app_include` (where we add `app/`) takes precedense over `in_app_exclude` (where we could add `app/Http/Middleware/`): https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#in-app-exclude. 

We obviously also don't want to modify the stacktraces too much to prevent us inadvertently messing them up or making them factually incorrect which would be even more bad.

But in these cases where you have _a lot_ of logic in a vendor package the in app frames are meh. Maybe you could add `vendor/laravel/nova/` to `in_app_include` to make the stacks from errors in Nova a little more clearer for you.

**Comment by webard** [comment]
Can we made `in_app_include` and `in_app_exclude` configurable from sentry.php? I'm thinking about removing `app/` from in_app_include and leaving it blank or making it more precise like `app/Controllers`, `app/Models` etc.

Generally in_app_exclude should have precendence over in_app_include, it makes more sense and would be more flexilbe.

**Comment by stayallive** [comment]
They are, just add them 😉

**Comment by cleptric** [comment]
As @stayallive wrote, this can be easily customised on the app level, using `in_app_include/in_app_exclude`. I don't think it's feasible to change any defaults.
