### ISSUE TITLE
Getting errors with cache tracing

### ISSUE THREAD

**Issue by ashwin-nath-m** [getsentry/sentry-laravel#916]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.7.0

### Steps to reproduce

{"message":"Object of class stdClass could not be converted to string","context":{"userId":61,"exception":{"class":"Error","message":"Object of class stdClass could not be converted to string","code":0,"file":"/var/www/xxx/releases/219/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Features/CacheIntegration.php:117"}},"level":400,"level_name":"ERROR","channel":"local","datetime":"2024-07-12T09:48:16.149984+00:00","extra":{}}

### Expected result

work

### Actual result

application crash

**Comment by ashwin-nath-m** [comment]
downgrading to 4.6.1 worked

**Comment by stayallive** [comment]
> Object of class stdClass could not be converted to string

And this happens when we do:

> implode(', ', $keys) // $keys come from the Laravel cache events

This tells me that you are caching stuff on a key that is not a string but an object?

Any clue what that might be and how that happened? That should not be possible unless I'm missing something!

**Comment by ryzr** [comment]
Here's a link to our stack trace: https://lumin-sports-technology.sentry.io/share/issue/ffe84e74551847a19ae53242e0e9d035/

I have a feeling it's due to Laravel allowing multidimensional arrays [$cacheKey => $defaultValue]
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Cache/Repository.php#L138-L147

**Comment by pataar** [comment]
![image](https://github.com/user-attachments/assets/c8bb2087-6fa0-4f33-acb0-aa82c0facc6b)

Same problem here. 

Called from the `kreait/laravel-firebase` package. Using this method:

![image](https://github.com/user-attachments/assets/a82d9410-2eb5-4545-8f7f-8f44e6d71139)

**Comment by ashwin-nath-m** [comment]
@pataar Nice find, i get this error when sending notifications using [laravel-notification-channels/fcm](https://github.com/laravel-notification-channels/fcm) which uses kreait/laravel-firebase upstream.

**Comment by stayallive** [comment]
Awesome, thanks both for your info! I will take a look at the package and see what we are doing wrong and fix it asap!

**Comment by stayallive** [comment]
I think I indeed found the issue and y'all were right on the money with the "multiple" cache operations causing issues. I think I implemented the events into Laravel core incorrectly and assumed we would only get an array of strings, but that is a false assumption since we get the original input so sometimes a multi-dimensional array with the (default) values too.

Long story short, should be fixed with #923. If it's possible to try this out it would be a great help validating I squashed it for real! You can try it by replacing `"sentry/sentry-laravel": "^4.7"` in your `composer.json` with `"sentry/sentry-laravel": "dev-cache-fixes@dev"` and running `composer update`.

We will probably release this soon anyway, but knowing it definitely fixes it would be great!

**Comment by cleptric** [comment]
A fix for this issue was released in [4.7.1](https://github.com/getsentry/sentry-laravel/releases/tag/4.7.1).
